### ISSUE TITLE
Investigate excessive long time test (>half hour) 

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1236]
### END testQueueJobsMaxCapacity at Fri Aug 07 01:57:57 PDT 2020, took: 2240047ms.

---------- Test Class TestWorkflowAndJobPoll thread leakage detected! ---------------
START testJobQueueAddingJobsAtSametime at Fri Aug 07 01:20:25 PDT 2020
END testJobQueueAddingJobsAtSametime at Fri Aug 07 01:20:27 PDT 2020, took: 2487ms.
START testJobQueueAddingJobsOneByOne at Fri Aug 07 01:20:27 PDT 2020
END testJobQueueAddingJobsOneByOne at Fri Aug 07 01:20:33 PDT 2020, took: 5983ms.
START testJobSubmitGenericWorkflows at Fri Aug 07 01:20:33 PDT 2020
END testJobSubmitGenericWorkflows at Fri Aug 07 01:20:37 PDT 2020, took: 4011ms.
START testQueueJobsMaxCapacity at Fri Aug 07 01:20:37 PDT 2020
END testQueueJobsMaxCapacity at Fri Aug 07 01:57:57 PDT 2020, took: 2240047ms.
START testQueueParallelJobs at Fri Aug 07 01:57:57 PDT 2020
4980696 [Timer-594] ERROR org.apache.helix.controller.GenericHelixController  - Time task failed. Rebalance task type: OnDemandRebalance, cluster: CLUSTER_TestTaskStage
org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
        at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:387)
        at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
        at org.apache.helix.controller.GenericHelixController$RebalanceTask.run(GenericHelixController.java:288)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
END testQueueParallelJobs at Fri Aug 07 03:45:34 PDT 2020, took: 6457223ms.
11399885 [HelixController-pipeline-default-CLUSTER_TestEnqueueJobs-(8c59dfb2_DEFAULT)] ERROR org.apache.helix.controller.GenericHelixController  - Cluster manager: controller_0 is not leader for CLUSTER_TestEnqueueJobs. Pipeline will not be invoked
TestEnqueueJobs has active threads cnt:1591
zookeeper server threads has 4 thread
Failure zkclient/zooKeeper session threads has 310 thread
0 thread:main-EventThread
1 thread:HelixController-pipeline-default-TestCorrectnessOnConnectivityLoss_testParticipant-(266a0c5b_DEFAULT)-EventThread
2 thread:main-EventThread

### END testQueueParallelJobs at Fri Aug 07 03:45:34 PDT 2020, took: 6457223ms.

https://github.com/apache/helix/issues/1235

### END testDeleteWorkflow at Fri Aug 07 08:20:23 PDT 2020, took: 16440073ms.

---------- Test Class TestFailTargetJobWhenResourceDisabled thread leakage detected! ---------------
START testDeleteHangingJobs at Fri Aug 07 03:46:22 PDT 2020
11448023 [HelixController-pipeline-task-CLUSTER_TestDeleteWorkflow-(ea5ec26f_TASK)] ERROR org.apache.helix.task.JobDispatcher  - Workflow configuration is NULL for testDeleteHangingJobs_job1
11448067 [HelixController-pipeline-task-CLUSTER_TestDeleteWorkflow-(ea2d4a87_TASK)] ERROR org.apache.helix.task.JobDispatcher  - Workflow configuration is NULL for testDeleteHangingJobs_job1
11448094 [HelixController-pipeline-task-CLUSTER_TestDeleteWorkflow-(8e5658da_TASK)] ERROR org.apache.helix.task.JobRebalancer  - Job testDeleteHangingJobs_job1's JobConfig is missing. This job might have been deleted or purged. Skippi
ng status update and assignment!
END testDeleteHangingJobs at Fri Aug 07 03:46:23 PDT 2020, took: 885ms.
START testDeleteWorkflow at Fri Aug 07 03:46:23 PDT 2020
END testDeleteWorkflow at Fri Aug 07 08:20:23 PDT 2020, took: 16440073ms.
START testDeleteWorkflowForcefully at Fri Aug 07 08:20:23 PDT 2020
END testDeleteWorkflowForcefully at Fri Aug 07 08:20:28 PDT 2020, took: 5133ms.
27893905 [HelixController-pipeline-task-CLUSTER_TestDeleteWorkflow-(da209494_TASK)] ERROR org.apache.helix.task.JobRebalancer  - Job testDeleteWorkflowForcefully_job1's JobConfig is missing. This job might have been deleted or purged. Skipping status update and assignment!
27893916 [HelixController-pipeline-default-CLUSTER_TestDeleteWorkflow-(54db1284_DEFAULT)] ERROR org.apache.helix.controller.GenericHelixController  - Exception while executing DEFAULT pipeline: CLUSTER_TestDeleteWorkflow for cluster [org.apache.helix.zookeeper.zkclient.ZkClient.retryUntilConnected(ZkClient.java:1683), org.apache.helix.zookeeper.zkclient.ZkClient.readData(ZkClient.java:1820), org.apache.helix.zookeeper.zkclient.ZkClient.readData(ZkClient.java:1812), org.apache.helix.manager.zk.ZkBaseDataAccessor.get(ZkBaseDataAccessor.java:474), org.apache.helix.manager.zk.ZKHelixDataAccessor.getProperty(ZKHelixDataAccessor.java:290), org.apache.helix.controller.dataproviders.ResourceControllerDataProvider.refreshCustomizedStateConfig(ResourceControllerDataProvider.java:187), org.apache.helix.controller.dataproviders.ResourceControllerDataProvider.refresh(ResourceControllerDataProvider.java:156), org.apache.helix.controller.stages.ReadClusterDataStage.process(ReadClusterDataStage.java:63), org.apache.helix.controller.pipeline.Pipeline.handle(Pipeline.java:68), org.apache.helix.controller.GenericHelixController.handleEvent(GenericHelixController.java:769), org.apache.helix.controller.GenericHelixController.access$500(GenericHelixController.java:128), org.apache.helix.controller.GenericHelixController$ClusterEventProcessor.run(GenericHelixController.java:1399)]. Will not continue to next pipeline
27893916 [HelixController-pipeline-task-CLUSTER_TestDeleteWorkflow-(54db1284_TASK)] ERROR org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks  - Interrupted waiting for success
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks$DefaultCallback.waitForSuccess(ZkAsyncCallbacks.java:220)
        at org.apache.helix.manager.zk.ZkBaseDataAccessor.getStats(ZkBaseDataAccessor.java:1198)
        at org.apache.helix.manager.zk.ZKHelixDataAccessor.getPropertyStats(ZKHelixDataAccessor.java:365)
        at org.apache.helix.common.caches.AbstractDataCache.refreshProperties(AbstractDataCache.java:66)
        at org.apache.helix.common.caches.ParticipantStateCache.refreshParticipantStatesCacheFromZk(ParticipantStateCache.java:122)
        at org.apache.helix.common.caches.ParticipantStateCache.refresh(ParticipantStateCache.java:62)
        at org.apache.helix.controller.dataproviders.BaseControllerDataProvider.doRefresh(BaseControllerDataProvider.java:342)
        at org.apache.helix.controller.dataproviders.WorkflowControllerDataProvider.refresh(WorkflowControllerDataProvider.java:88)
        at org.apache.helix.controller.stages.ReadClusterDataStage.process(ReadClusterDataStage.java:63)
        at org.apache.helix.controller.pipeline.Pipeline.handle(Pipeline.java:68)
        at org.apache.helix.controller.GenericHelixController.handleEvent(GenericHelixController.java:769)
        at org.apache.helix.controller.GenericHelixController.access$500(GenericHelixController.java:128)
        at org.apache.helix.controller.GenericHelixController$ClusterEventProcessor.run(GenericHelixController.java:1399)
TestDeleteWorkflow has active threads cnt:1603
zookeeper server threads has 4 thread
Failure zkclient/zooKeeper session threads has 314 thread
0 thread:main-EventThread

### END testWorkflowContextWithoutConfig at Fri Aug 07 09:03:28 PDT 2020, took: 444367ms.
29991725 [TaskStateModelFactory-task_thread-17] ERROR org.apache.helix.task.TaskRunner  - Problem running the task, report task as FAILED.
org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
        at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:387)
        at org.apache.helix.manager.zk.ZKHelixManager.getHelixPropertyStore(ZKHelixManager.java:1012)
        at org.apache.helix.task.UserContentStore.getUserContent(UserContentStore.java:102)
        at org.apache.helix.integration.task.MockTask.run(MockTask.java:149)
        at org.apache.helix.task.TaskRunner.run(TaskRunner.java:71)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
29991726 [TaskStateModelFactory-task_thread-17] ERROR org.apache.helix.task.TaskRunner  - Problem running the task, report task as FAILED.
org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
        at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:387)
        at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
        at org.apache.helix.task.TaskRunner.requestStateTransition(TaskRunner.java:184)
        at org.apache.helix.task.TaskRunner.run(TaskRunner.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
29991734 [HelixTaskExecutor-message_handle_thread] ERROR org.apache.helix.messaging.handling.HelixStateTransitionHandler  - Exception while executing a state transition task testStopWorkflowInStoppingState_Job1_0
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.helix.messaging.handling.HelixStateTransitionHandler.invoke(HelixStateTransitionHandler.java:404)
        at org.apache.helix.messaging.handling.HelixStateTransitionHandler.handleMessage(HelixStateTransitionHandler.java:331)
        at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:97)
        at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at org.apache.helix.task.TaskStateModel.onBecomeStoppedFromRunning(TaskStateModel.java:94)
        ... 11 more
29991735 [HelixTaskExecutor-message_handle_thread] ERROR org.apache.helix.util.StatusUpdateUtil  - Exception while logging status update
org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
        at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:387)
        at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
        at org.apache.helix.util.StatusUpdateUtil.logMessageStatusUpdateRecord(StatusUpdateUtil.java:349)
        at org.apache.helix.util.StatusUpdateUtil.logError(StatusUpdateUtil.java:401)
        at org.apache.helix.messaging.handling.HelixStateTransitionHandler.handleMessage(HelixStateTransitionHandler.java:359)
        at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:97)
        at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
29991735 [HelixTaskExecutor-message_handle_thread] ERROR org.apache.helix.messaging.handling.HelixTask  - Exception while executing a message. org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect() msgId: 3da68b53-d3d3-40ef-a4ed-8a492ad692d1 type: STATE_TRANSITION
org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
        at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:387)
        at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
        at org.apache.helix.messaging.handling.HelixStateTransitionHandler.postHandleMessage(HelixStateTransitionHandler.java:191)
        at org.apache.helix.messaging.handling.HelixStateTransitionHandler.handleMessage(HelixStateTransitionHandler.java:371)
        at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:97)
        at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
29991735 [HelixTaskExecutor-message_handle_thread] ERROR org.apache.helix.util.StatusUpdateUtil  - Exception while logging status update
org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
        at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:387)
        at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
        at org.apache.helix.util.StatusUpdateUtil.logMessageStatusUpdateRecord(StatusUpdateUtil.java:349)
        at org.apache.helix.util.StatusUpdateUtil.logError(StatusUpdateUtil.java:401)
        at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:119)
        at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
29991735 [HelixTaskExecutor-message_handle_thread] ERROR org.apache.helix.messaging.handling.HelixTask  - Message execution failed. msgId: 3da68b53-d3d3-40ef-a4ed-8a492ad692d1, errorMsg: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
29991736 [HelixTaskExecutor-message_handle_thread] ERROR org.apache.helix.util.StatusUpdateUtil  - Exception while logging status update
org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
        at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:387)
        at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
        at org.apache.helix.util.StatusUpdateUtil.logMessageStatusUpdateRecord(StatusUpdateUtil.java:349)
        at org.apache.helix.util.StatusUpdateUtil.logError(StatusUpdateUtil.java:393)
        at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:166)
        at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
29991736 [HelixTaskExecutor-message_handle_thread] ERROR org.apache.helix.messaging.handling.HelixTask  - Error to final clean up for message : 3da68b53-d3d3-40ef-a4ed-8a492ad692d1
29991736 [HelixTaskExecutor-message_handle_thread] ERROR org.apache.helix.messaging.handling.HelixTask  - Exception after executing a message, msgId: 3da68b53-d3d3-40ef-a4ed-8a492ad692d1org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
        at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:387)
        at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
        at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:172)
        at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
29991736 [HelixTaskExecutor-message_handle_thread] ERROR org.apache.helix.util.StatusUpdateUtil  - Exception while logging status update
org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
        at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:387)
        at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
        at org.apache.helix.util.StatusUpdateUtil.logMessageStatusUpdateRecord(StatusUpdateUtil.java:349)
        at org.apache.helix.util.StatusUpdateUtil.logError(StatusUpdateUtil.java:393)
        at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:195)
        at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
START testWorkflowContextGarbageCollection at Fri Aug 07 08:55:28 PDT 2020
30012417 [HelixController-pipeline-default-CLUSTER_TestWorkflowContextWithoutConfig-(66ace32d_DEFAULT)] ERROR org.apache.helix.controller.GenericHelixController  - Exception while executing DEFAULT pipeline: CLUSTER_TestWorkflowContextWithoutConfig for cluster [org.apache.helix.zookeeper.zkclient.ZkClient.retryUntilConnected(ZkClient.java:1683), org.apache.helix.zookeeper.zkclient.ZkClient.getChildren(ZkClient.java:1038), org.apache.helix.zookeeper.zkclient.ZkClient.getChildren(ZkClient.java:1031), org.apache.helix.manager.zk.ZkBaseDataAccessor.getChildNames(ZkBaseDataAccessor.java:670), org.apache.helix.manager.zk.ZKHelixDataAccessor.getChildNames(ZKHelixDataAccessor.java:394), org.apache.helix.common.caches.CurrentStateCache.PopulateParticipantKeys(CurrentStateCache.java:63), org.apache.helix.common.caches.ParticipantStateCache.refreshParticipantStatesCacheFromZk(ParticipantStateCache.java:111), org.apache.helix.common.caches.ParticipantStateCache.refresh(ParticipantStateCache.java:62), org.apache.helix.controller.dataproviders.BaseControllerDataProvider.doRefresh(BaseControllerDataProvider.java:342), org.apache.helix.controller.dataproviders.ResourceControllerDataProvider.refresh(ResourceControllerDataProvider.java:143), org.apache.helix.controller.stages.ReadClusterDataStage.process(ReadClusterDataStage.java:63), org.apache.helix.controller.pipeline.Pipeline.handle(Pipeline.java:68), org.apache.helix.controller.GenericHelixController.handleEvent(GenericHelixController.java:769), org.apache.helix.controller.GenericHelixController.access$500(GenericHelixController.java:128), org.apache.helix.controller.GenericHelixController$ClusterEventProcessor.run(GenericHelixController.java:1399)]. Will not continue to next pipeline
30012418 [HelixController-pipeline-task-CLUSTER_TestWorkflowContextWithoutConfig-(66ace32d_TASK)] ERROR org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks  - Interrupted waiting for success
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks$DefaultCallback.waitForSuccess(ZkAsyncCallbacks.java:220)
        at org.apache.helix.manager.zk.ZkBaseDataAccessor.getStats(ZkBaseDataAccessor.java:1198)
        at org.apache.helix.manager.zk.ZKHelixDataAccessor.getPropertyStats(ZKHelixDataAccessor.java:365)
        at org.apache.helix.common.caches.AbstractDataCache.refreshProperties(AbstractDataCache.java:66)
        at org.apache.helix.common.caches.PropertyCache.doRefreshWithSelectiveUpdate(PropertyCache.java:175)
        at org.apache.helix.common.caches.PropertyCache.refresh(PropertyCache.java:158)
        at org.apache.helix.controller.dataproviders.BaseControllerDataProvider.refreshInstanceConfigs(BaseControllerDataProvider.java:269)
        at org.apache.helix.controller.dataproviders.BaseControllerDataProvider.doRefresh(BaseControllerDataProvider.java:331)
        at org.apache.helix.controller.dataproviders.WorkflowControllerDataProvider.refresh(WorkflowControllerDataProvider.java:88)
        at org.apache.helix.controller.stages.ReadClusterDataStage.process(ReadClusterDataStage.java:63)
        at org.apache.helix.controller.pipeline.Pipeline.handle(Pipeline.java:68)
        at org.apache.helix.controller.GenericHelixController.handleEvent(GenericHelixController.java:769)
        at org.apache.helix.controller.GenericHelixController.access$500(GenericHelixController.java:128)
        at org.apache.helix.controller.GenericHelixController$ClusterEventProcessor.run(GenericHelixController.java:1399)
30015649 [Timer-2059] ERROR org.apache.helix.controller.GenericHelixController  - Time task failed. Rebalance task type: OnDemandRebalance, cluster: CLUSTER_TestTaskRebalancerStopResume
org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
        at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:387)
        at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
        at org.apache.helix.controller.GenericHelixController$RebalanceTask.run(GenericHelixController.java:288)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
END testWorkflowContextGarbageCollection at Fri Aug 07 08:56:03 PDT 2020, took: 35279ms.
START testWorkflowContextWithoutConfig at Fri Aug 07 08:56:03 PDT 2020
30029648 [Timer-2059] ERROR org.apache.helix.controller.GenericHelixController  - Time task failed. Rebalance task type: OnDemandRebalance, cluster: CLUSTER_TestTaskRebalancerStopResume
org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
        at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:387)
        at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
        at org.apache.helix.controller.GenericHelixController$RebalanceTask.run(GenericHelixController.java:288)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
30036469 [Timer-2059] ERROR org.apache.helix.controller.GenericHelixController  - Time task failed. Rebalance task type: OnDemandRebalance, cluster: CLUSTER_TestTaskRebalancerStopResume
org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
        at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:387)
        at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
        at org.apache.helix.controller.GenericHelixController$RebalanceTask.run(GenericHelixController.java:288)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
END testWorkflowContextWithoutConfig at Fri Aug 07 09:03:28 PDT 2020, took: 444367ms.
30473247 [HelixController-pipeline-default-CLUSTER_TestWorkflowContextWithoutConfig-(0c3b9b9e_DEFAULT)] ERROR org.apache.helix.controller.GenericHelixController  - Cluster manager: controller_0 is not leader for CLUSTER_TestWorkflowContextWithoutConfig. Pipeline will not be invoked
TestWorkflowContextWithoutConfig has active threads cnt:1610
zookeeper server threads has 4 thread
Failure zkclient/zooKeeper session threads has 314 thread
0 thread:main-EventThread

### END testWorkflowPausedTimeout at Fri Aug 07 11:22:12 PDT 2020, took: 8280583ms.

https://github.com/apache/helix/issues/1234

**Comment by jiajunwang** [comment]
Cannot reproduce.
