### ISSUE TITLE
Fix flaky TestWagedRebalance.testChangeIdealState which fails a lot

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1267]
Example log:
>2020-08-12T12:38:16.1210485Z [ERROR] testChangeIdealState(org.apache.helix.integration.rebalancer.WagedRebalancer.TestWagedRebalance)  Time elapsed: 6.137 s  <<< FAILURE!
2020-08-12T12:38:16.1220719Z java.lang.AssertionError: expected:<true> but was:<false>
2020-08-12T12:38:16.1227589Z         at org.apache.helix.integration.rebalancer.WagedRebalancer.TestWagedRebalance.validate(TestWagedRebalance.java:646)
2020-08-12T12:38:16.1230951Z         at org.apache.helix.integration.rebalancer.WagedRebalancer.TestWagedRebalance.testChangeIdealState(TestWagedRebalance.java:303)
2020-08-12T12:38:16.1231145Z

**Comment by kaisun2000** [comment]
@jiajunwang, please add the pull request addressing this issue.

**Comment by jiajunwang** [comment]
This PR is supposed to fix it. #1256

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
