### ISSUE TITLE
Fix flaky test TestResourceChangeDetector

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1281]
LOG:
>2020-08-14T10:56:36.2278432Z [ERROR]   TestResourceChangeDetector.testResetSnapshots:449 expected:<0> but was:<1>

2020-08-14T10:56:35.8572321Z [ERROR] testResetSnapshots(org.apache.helix.controller.changedetector.TestResourceChangeDetector)  Time elapsed: 0.107 s  <<< FAILURE!
2020-08-14T10:56:35.8573105Z java.lang.AssertionError: expected:<0> but was:<1>
2020-08-14T10:56:35.8580562Z 	at org.apache.helix.controller.changedetector.TestResourceChangeDetector.testResetSnapshots(TestResourceChangeDetector.java:449)
2020-08-14T10:56:35.8580884Z

**Comment by kaisun2000** [comment]
Another problem is not close StrictMatchExternalViewVerifier, leak resource.

THis one needs further examination.

**Comment by kaisun2000** [comment]
Failed another time. Need further examination.

**Comment by kaisun2000** [comment]
Added more log in StrictMatchExternalViewVerifier, trigger callback. Change waiting time to 15 mins , same as timeout for test.

**Comment by kaisun2000** [comment]
#1227

**Comment by kaisun2000** [comment]
one more time:

>2020-09-15T23:51:12.8993411Z [ERROR] Tests run: 1197, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 4,741.919 s <<< FAILURE! - in TestSuite
2020-09-15T23:51:12.8995084Z [ERROR] testResetSnapshots(org.apache.helix.controller.changedetector.TestResourceChangeDetector)  Time elapsed: 300.038 s  <<< FAILURE!
2020-09-15T23:51:12.8996657Z java.lang.AssertionError: expected:<true> but was:<false>
2020-09-15T23:51:12.8998840Z 	at org.apache.helix.controller.changedetector.TestResourceChangeDetector.testResetSnapshots(TestResourceChangeDetector.java:438)
2020-09-15T23:51:12.9000831Z 
2020-09-15T23:51:13.2757259Z [ERROR] Failures: 
2020-09-15T23:51:13.2760957Z [ERROR]   TestResourceChangeDetector.testResetSnapshots:438 expected:<true> but was:<false>
2020-09-15T23:51:13.2764093Z [ERROR] Tests run: 1197, Failures: 1, Errors: 0, Skipped: 1

**Comment by kaisun2000** [comment]
another time: log 910

> 2020-09-16T00:02:24.5744481Z [ERROR] Tests run: 1197, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 5,053.729 s <<< FAILURE! - in TestSuite
2020-09-16T00:02:24.5756583Z [ERROR] testResetSnapshots(org.apache.helix.controller.changedetector.TestResourceChangeDetector)  Time elapsed: 300.064 s  <<< FAILURE!
2020-09-16T00:02:24.5762923Z java.lang.AssertionError: expected:<true> but was:<false>
2020-09-16T00:02:24.5774608Z 	at org.apache.helix.controller.changedetector.TestResourceChangeDetector.testResetSnapshots(TestResourceChangeDetector.java:438)
2020-09-16T00:02:24.5778019Z 
2020-09-16T00:02:24.9729877Z [ERROR] Failures: 
2020-09-16T00:02:24.9732038Z [ERROR]   TestResourceChangeDetector.testResetSnapshots:438 expected:<true> but was:<false>
2020-09-16T00:02:24.9735460Z [ERROR] Tests run: 1197, Failures: 1, Errors: 0, Skipped: 1
2020-09-16T00:02:24.9803925Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project helix-core: There are test failures.
2020-09-16T00:02:24.9816989Z [ERROR]

**Comment by kaisun2000** [comment]
increase time out as now verify would timeout in 5 mintues by default.

**Comment by kaisun2000** [comment]
log 930 first batch of waitTillVerify
>2020-09-17T01:20:49.7767264Z [ERROR]   TestResourceChangeDetector.testResetSnapshots:437 » ThreadTimeout Method org.t...

code 

```
  public void testResetSnapshots() {
    // ensure the cluster converged before the test to ensure IS is not modified unexpectedly
    ZkHelixClusterVerifier _clusterVerifier =
        new StrictMatchExternalViewVerifier.Builder(CLUSTER_NAME).setZkAddress(ZK_ADDR)
            .setDeactivatedNodeAwareness(true)
            .setResources(new HashSet<>(_dataAccessor.getChildNames(_keyBuilder.idealStates())))
            .setWaitTillVerify(TestHelper.DEFAULT_REBALANCE_PROCESSING_WAIT_TIME)
            .build();
    try {
      boolean result = _clusterVerifier.verify(WAIT_TIME);   ----- this line.
      Assert.assertTrue(result);
    } finally {
      _clusterVerifier.close();
    }


```

**Comment by kaisun2000** [comment]
2020-09-17T01:20:49.3991835Z [ERROR] testResetSnapshots(org.apache.helix.controller.changedetector.TestResourceChangeDetector)  Time elapsed: 1,800.007 s  <<< FAILURE!
2020-09-17T01:20:49.3995272Z org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testResetSnapshots() didn't finish within the time-out 1800000
2020-09-17T01:20:49.3999251Z 	at org.apache.helix.controller.changedetector.TestResourceChangeDetector.testResetSnapshots(TestResourceChangeDetector.java:437)
2020-09-17T01:20:49.4001707Z 
2020-09-17T01:20:49.4003183Z [ERROR]

**Comment by kaisun2000** [comment]
LOG 969, touch 3

>2020-09-17T09:51:57.3363039Z [ERROR] testResetSnapshots(org.apache.helix.controller.changedetector.TestResourceChangeDetector)  Time elapsed: 1,800.015 s  <<< FAILURE!
2020-09-17T09:51:57.3413951Z org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testResetSnapshots() didn't finish within the time-out 1800000
2020-09-17T09:51:57.3418048Z 	at org.apache.helix.controller.changedetector.TestResourceChangeDetector.testResetSnapshots(TestResourceChangeDetector.java:437)
2020-09-17T09:51:57.3420607Z 
2020-09-17T09:51:57.7154562Z [ERROR] Failures: 
2020-09-17T09:51:57.7156522Z [ERROR]   TestResourceChangeDetector.testResetSnapshots:437 » ThreadTimeout Method org.t...

**Comment by kaisun2000** [comment]
LOG 973, touch 5
>2020-09-17T09:51:57.3363039Z [ERROR] testResetSnapshots(org.apache.helix.controller.changedetector.TestResourceChangeDetector)  Time elapsed: 1,800.015 s  <<< FAILURE!
2020-09-17T09:51:57.3413951Z org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testResetSnapshots() didn't finish within the time-out 1800000
2020-09-17T09:51:57.3418048Z 	at org.apache.helix.controller.changedetector.TestResourceChangeDetector.testResetSnapshots(TestResourceChangeDetector.java:437)
2020-09-17T09:51:57.3420607Z 
2020-09-17T09:51:57.7154562Z [ERROR] Failures: 
2020-09-17T09:51:57.7156522Z [ERROR]   TestResourceChangeDetector.testResetSnapshots:437 » ThreadTimeout Method org.t...

**Comment by kaisun2000** [comment]
LOG 1051, 09/18 touch 3
> 2020-09-18T11:14:08.7558906Z [ERROR] testResetSnapshots(org.apache.helix.controller.changedetector.TestResourceChangeDetector)  Time elapsed: 1,800.014 s  <<< FAILURE!
2020-09-18T11:14:08.7685856Z org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testResetSnapshots() didn't finish within the time-out 1800000
2020-09-18T11:14:08.7698996Z 	at org.apache.helix.controller.changedetector.TestResourceChangeDetector.testResetSnapshots(TestResourceChangeDetector.java:437)
2020-09-18T11:14:08.7702496Z 
2020-09-18T11:14:09.1585373Z [ERROR] Failures: 
2020-09-18T11:14:09.1588655Z [ERROR]   TestResourceChangeDetector.testResetSnapshots:437 » ThreadTimeout Method org.t...
2020-09-18T11:14:09.1590014Z [ERROR] Tests run: 1196, Failures: 1, Errors: 0, Skipped: 1

**Comment by kaisun2000** [comment]
LOG 1061, 09/18 touch 9

>2020-09-18T11:18:01.3541498Z [ERROR]   TestResourceChangeDetector.testResetSnapshots:437 » ThreadTimeout Method org.t...
2020-09-18T11:18:01.3547252Z [ERROR] Tests run: 1196, Failures: 1, Errors: 0, Skipped: 1

**Comment by kaisun2000** [comment]
LOG 1118. fix #1367 

>2020-09-21T04:56:36.3191026Z [ERROR] testResetSnapshots(org.apache.helix.controller.changedetector.TestResourceChangeDetector)  Time elapsed: 1,800.026 s  <<< FAILURE!
2020-09-21T04:56:36.3203620Z org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testResetSnapshots() didn't finish within the time-out 1800000
2020-09-21T04:56:36.3215445Z 	at org.apache.helix.controller.changedetector.TestResourceChangeDetector.testResetSnapshots(TestResourceChangeDetector.java:437)
2020-09-21T04:56:36.3219010Z 
2020-09-21T04:56:36.6976619Z [ERROR] Failures: 
2020-09-21T04:56:36.6982617Z [ERROR]   TestResourceChangeDetector.testResetSnapshots:437 » ThreadTimeout Method org.t...
2020-09-21T04:56:36.7005986Z [ERROR] Tests run: 1196, Failures: 1, Errors: 0, Skipped: 1
2020-09-21T04:56:36.7054647Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project helix-core: There are test failures.

**Comment by kaisun2000** [comment]
LOG 1113 09/20 touch 8
>2020-09-20T22:23:33.9435500Z [ERROR] testResetSnapshots(org.apache.helix.controller.changedetector.TestResourceChangeDetector)  Time elapsed: 1,800.016 s  <<< FAILURE!
2020-09-20T22:23:33.9447133Z org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testResetSnapshots() didn't finish within the time-out 1800000
2020-09-20T22:23:33.9466054Z 	at org.apache.helix.controller.changedetector.TestResourceChangeDetector.testResetSnapshots(TestResourceChangeDetector.java:437)
2020-09-20T22:23:33.9468916Z 
2020-09-20T22:23:34.3349605Z [ERROR] Failures: 
2020-09-20T22:23:34.3355817Z [ERROR]   TestResourceChangeDetector.testResetSnapshots:437 » ThreadTimeout Method org.t...
2020-09-20T22:23:34.3357545Z [ERROR] Tests run: 1196, Failures: 1, Errors: 0, Skipped: 1
2020-09-20T22:23:34.3438853Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project helix-core: There are test failures.
2020-09-20T22:23:34.3464788Z [ERROR]

**Comment by kaisun2000** [comment]
LOG 1109, 09/20 touch 5
>2020-09-20T22:19:50.9503891Z [ERROR] Tests run: 1196, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 6,338.181 s <<< FAILURE! - in TestSuite
2020-09-20T22:19:50.9506411Z [ERROR] testResetSnapshots(org.apache.helix.controller.changedetector.TestResourceChangeDetector)  Time elapsed: 1,800.013 s  <<< FAILURE!
2020-09-20T22:19:50.9511011Z org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testResetSnapshots() didn't finish within the time-out 1800000
2020-09-20T22:19:50.9514789Z 	at org.apache.helix.controller.changedetector.TestResourceChangeDetector.testResetSnapshots(TestResourceChangeDetector.java:440)
2020-09-20T22:19:50.9517051Z 
2020-09-20T22:19:51.3291033Z [ERROR] Failures: 
2020-09-20T22:19:51.3298448Z [ERROR]   TestResourceChangeDetector.testResetSnapshots:440->Object.wait:-2 » ThreadTimeout
2020-09-20T22:19:51.3299552Z [ERROR] Tests run: 1196, Failures: 1, Errors: 0, Skipped: 1
2020-09-20T22:19:51.3372077Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project helix-core: There are test failures.

**Comment by kaisun2000** [comment]
public void testIgnoreNonTopologyChanges()

delete full auto resource added.

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
