### ISSUE TITLE
Fix flaky test TestTaskRebalancerParallel.testWhenAllowOverlapJobAssignment

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1283]
LOG:
>2020-08-16T04:10:36.5238670Z [ERROR]   TestTaskRebalancerParallel.testWhenAllowOverlapJobAssignment:125 expected:< true > but was:< false >

> 2020-08-16T04:10:36.1700878Z [ERROR] testWhenAllowOverlapJobAssignment(org.apache.helix.integration.task.TestTaskRebalancerParallel)  Time elapsed: 6.21 s  <<< FAILURE!
2020-08-16T04:10:36.1701274Z java.lang.AssertionError: expected:<true> but was:<false>
2020-08-16T04:10:36.1702924Z 	at org.apache.helix.integration.task.TestTaskRebalancerParallel.testWhenAllowOverlapJobAssignment(TestTaskRebalancerParallel.java:125)

Code:
```
  // 1. Different jobs in a same work flow is in RUNNING at the same time
  // 2. When disallow overlap assignment, no two jobs in the same work flow is in RUNNING at the same instance
  // Use this method with caution because it assumes workflow doesn't finish too quickly and number of parallel running
  // tasks can be counted.
  public static boolean pollForWorkflowParallelState(TaskDriver driver, String workflowName)
      throws InterruptedException {

    WorkflowConfig workflowConfig = driver.getWorkflowConfig(workflowName);
    Assert.assertNotNull(workflowConfig);

    WorkflowContext workflowContext = null;
    while (workflowContext == null) {
      workflowContext = driver.getWorkflowContext(workflowName);
      Thread.sleep(100);
    }

    int maxRunningCount = 0;
    boolean finished = false;

    while (!finished) {
      finished = true;
      int runningCount = 0;

      workflowContext = driver.getWorkflowContext(workflowName);
      for (String jobName : workflowConfig.getJobDag().getAllNodes()) {
        TaskState jobState = workflowContext.getJobState(jobName);
        if (jobState == TaskState.IN_PROGRESS) {
          ++runningCount;
          finished = false;
        }
      }

      if (runningCount > maxRunningCount ) {
        maxRunningCount = runningCount;
      }

      Thread.sleep(100);
    }

    List<JobContext> jobContextList = new ArrayList<>();
    for (String jobName : workflowConfig.getJobDag().getAllNodes()) {
      JobContext jobContext = driver.getJobContext(jobName);
      if (jobContext != null) {
        jobContextList.add(driver.getJobContext(jobName));
      }
    }
    Map<String, List<long[]>> rangeMap = new HashMap<>();

    if (!workflowConfig.isAllowOverlapJobAssignment()) {
      for (JobContext jobContext : jobContextList) {
        for (int partition : jobContext.getPartitionSet()) {
          String instance = jobContext.getAssignedParticipant(partition);
          if (!rangeMap.containsKey(instance)) {
            rangeMap.put(instance, new ArrayList<long[]>());
          }
          rangeMap.get(instance).add(new long[] { jobContext.getPartitionStartTime(partition),
              jobContext.getPartitionFinishTime(partition)
          });
        }
      }
    }

    for (List<long[]> timeRange : rangeMap.values()) {
      Collections.sort(timeRange, new Comparator<long[]>() {
        @Override
        public int compare(long[] o1, long[] o2) {
          return (int) (o1[0] - o2[0]);
        }
      });

      for (int i = 0; i < timeRange.size() - 1; i++) {
        if (timeRange.get(i)[1] > timeRange.get(i + 1)[0]) {
          return false;
        }
      }
    }
    return maxRunningCount > 1 && (workflowConfig.isJobQueue() ? maxRunningCount <= workflowConfig
        .getParallelJobs() : true);
}
```

Not sure where it goes wrong as this function returned false. Add more logging when return failure.

**Comment by kaisun2000** [comment]
LOG 1505
>2020-09-25T08:34:08.8679889Z [ERROR] testWhenAllowOverlapJobAssignment(org.apache.helix.integration.task.TestTaskRebalancerParallel)  Time elapsed: 5.044 s  <<< FAILURE!
2020-09-25T08:34:08.8681703Z java.lang.AssertionError: expected:<true> but was:<false>
2020-09-25T08:34:08.8684400Z 	at org.apache.helix.integration.task.TestTaskRebalancerParallel.testWhenAllowOverlapJobAssignment(TestTaskRebalancerParallel.java:124)
2020-09-25T08:34:08.8689680Z

**Comment by kaisun2000** [comment]
> 020-09-25T07:32:34.9743253Z START TestTaskRebalancerParallel testWhenAllowOverlapJobAssignment at Fri Sep 25 07:32:34 UTC 2020
2020-09-25T07:32:35.0858323Z 806312 [HelixController-pipeline-task-CLUSTER_TestTaskRebalancerParallel-(2bbe73bc_TASK)] ERROR org.apache.helix.task.AbstractTaskDispatcher  - The job config is missing for job testWhenAllowOverlapJobAssignment_job_2
2020-09-25T07:32:40.0085596Z 811229 [TestNGInvoker-testWhenAllowOverlapJobAssignment()] ERROR org.apache.helix.integration.task.TaskTestUtil  - maxRunningCount=1, workflowConfig.isJobQueue()=true, maxRunningCount=1, workflowConfig.getParallelJobs()=2, stack trace [java.lang.Thread.getStackTrace(Thread.java:1559), org.apache.helix.integration.task.TaskTestUtil.pollForWorkflowParallelState(TaskTestUtil.java:185), org.apache.helix.integration.task.TestTaskRebalancerParallel.testWhenAllowOverlapJobAssignment(TestTaskRebalancerParallel.java:124), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76), org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46), org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511), java.util.concurrent.FutureTask.run(FutureTask.java:266), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)]
2020-09-25T07:32:40.0116320Z END TestTaskRebalancerParallel testWhenAllowOverlapJobAssignment at Fri Sep 25 07:32:40 UTC 2020, took: 5043ms.

**Comment by kaisun2000** [comment]
```
    boolean retVal =  maxRunningCount > 1 && (workflowConfig.isJobQueue() ? maxRunningCount <= workflowConfig
        .getParallelJobs() : true);
    if (!retVal) {
      logger.error("maxRunningCount={}, workflowConfig.isJobQueue()={}, maxRunningCount={}, workflowConfig.getParallelJobs()={}, stack trace {}",
          maxRunningCount, workflowConfig.isJobQueue(), maxRunningCount, workflowConfig.getParallelJobs(),
          Arrays.asList(Thread.currentThread().getStackTrace()));
    }
```

**Comment by kaisun2000** [comment]
// 1. Different jobs in a same work flow is in RUNNING at the same time
  // 2. When disallow overlap assignment, no two jobs in the same work flow is in RUNNING at the same instance
  // Use this method with caution because it assumes workflow doesn't finish too quickly and number of parallel running
  // tasks can be counted.

**Comment by kaisun2000** [comment]
two points. 

1/ add some delay for the job 
2/ batch queue the two jobs.

the code is like this now:

```
    // Create jobs that can be assigned to any instances
    List<JobConfig.Builder> jobConfigBuilders = new ArrayList<JobConfig.Builder>();
    for (int i = 0; i < PARALLEL_COUNT; i++) {
      List<TaskConfig> taskConfigs = new ArrayList<TaskConfig>();
      for (int j = 0; j < TASK_COUNT; j++) {
        taskConfigs.add(new TaskConfig.Builder()
            .setTaskId("job_" + (i + 1) + "_task_" + j)
            .setCommand(MockTask.TASK_COMMAND)
            .addConfig(MockTask.JOB_DELAY, "2000")
            .build());
      }
      jobConfigBuilders.add(new JobConfig.Builder().addTaskConfigs(taskConfigs));
    }

    _driver.stop(queueName);
    List<String> jobNames = new ArrayList<>();
    for (int i = 0; i < jobConfigBuilders.size(); ++i) {
      jobNames.add("job_" + (i + 1));
      //_driver.enqueueJob(queueName, "job_" + (i + 1), jobConfigBuilders.get(i));
    }
    _driver.enqueueJobs(queueName, jobNames, jobConfigBuilders);
    _driver.resume(queueName);
    Thread.sleep(2000);
    Assert.assertTrue(TaskTestUtil.pollForWorkflowParallelState(_driver, queueName));

```

**Comment by kaisun2000** [comment]
Still now working.

LOG 1689

>2020-09-26T04:28:38.1295285Z START TestTaskRebalancerParallel testWhenAllowOverlapJobAssignment at Sat Sep 26 04:28:38 UTC 2020
2020-09-26T04:28:38.2308857Z 790783 [HelixController-pipeline-task-CLUSTER_TestTaskRebalancerParallel-(b20c967f_TASK)] ERROR org.apache.helix.task.AbstractTaskDispatcher  - The job config is missing for job testWhenAllowOverlapJobAssignment_job_2
2020-09-26T04:29:40.1296989Z 852674 [TestNGInvoker-testWhenAllowOverlapJobAssignment()] ERROR org.apache.helix.integration.task.TaskTestUtil  - maxRunningCount=1, workflowConfig.isJobQueue()=true, maxRunningCount=1, workflowConfig.getParallelJobs()=2, stack trace [java.lang.Thread.getStackTrace(Thread.java:1559), org.apache.helix.integration.task.TaskTestUtil.pollForWorkflowParallelState(TaskTestUtil.java:185), org.apache.helix.integration.task.TestTaskRebalancerParallel.testWhenAllowOverlapJobAssignment(TestTaskRebalancerParallel.java:130), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76), org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46), org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511), java.util.concurrent.FutureTask.run(FutureTask.java:266), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)]
2020-09-26T04:29:40.1362846Z END TestTaskRebalancerParallel testWhenAllowOverlapJobAssignment at Sat Sep 26 04:29:40 UTC 2020, took: 62007ms.

**Comment by kaisun2000** [comment]
LOG 1783

>2020-09-27T00:50:37.6896172Z START TestTaskRebalancerParallel testWhenAllowOverlapJobAssignment at Sun Sep 27 00:50:37 UTC 2020
2020-09-27T00:50:37.8062579Z 810608 [HelixController-pipeline-task-CLUSTER_TestTaskRebalancerParallel-(1c5b8721_TASK)] ERROR org.apache.helix.task.AbstractTaskDispatcher  - The job config is missing for job testWhenAllowOverlapJobAssignment_job_2, with stacktrace [java.lang.Thread.getStackTrace(Thread.java:1559), org.apache.helix.task.AbstractTaskDispatcher.isJobReadyToSchedule(AbstractTaskDispatcher.java:1200), org.apache.helix.task.WorkflowDispatcher.scheduleJobs(WorkflowDispatcher.java:292), org.apache.helix.task.WorkflowDispatcher.assignWorkflow(WorkflowDispatcher.java:219), org.apache.helix.controller.stages.task.TaskSchedulingStage.scheduleWorkflows(TaskSchedulingStage.java:184), org.apache.helix.controller.stages.task.TaskSchedulingStage.compute(TaskSchedulingStage.java:101), org.apache.helix.controller.stages.task.TaskSchedulingStage.process(TaskSchedulingStage.java:89), org.apache.helix.controller.pipeline.Pipeline.handle(Pipeline.java:68), org.apache.helix.controller.GenericHelixController.handleEvent(GenericHelixController.java:777), org.apache.helix.controller.GenericHelixController.access$500(GenericHelixController.java:128), org.apache.helix.controller.GenericHelixController$ClusterEventProcessor.run(GenericHelixController.java:1407)]
2020-09-27T00:51:40.1946166Z 872993 [TestNGInvoker-testWhenAllowOverlapJobAssignment()] ERROR org.apache.helix.integration.task.TaskTestUtil  - maxRunningCount=1, workflowConfig.isJobQueue()=true, maxRunningCount=1, workflowConfig.getParallelJobs()=2, stack trace [java.lang.Thread.getStackTrace(Thread.java:1559), org.apache.helix.integration.task.TaskTestUtil.pollForWorkflowParallelState(TaskTestUtil.java:185), org.apache.helix.integration.task.TestTaskRebalancerParallel.testWhenAllowOverlapJobAssignment(TestTaskRebalancerParallel.java:130), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76), org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46), org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511), java.util.concurrent.FutureTask.run(FutureTask.java:266), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)]
2020-09-27T00:51:40.2079962Z END TestTaskRebalancerParallel testWhenAllowOverlapJobAssignment at Sun Sep 27 00:51:40 UTC 2020, took: 62512ms.

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
