### ISSUE TITLE
Fix unstable test TestEnqueueJobs.testJobQueueAddingJobsAtSametime

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1310]
LOG: (430)
>2020-08-24T22:13:51.0334014Z [ERROR] testJobQueueAddingJobsAtSametime(org.apache.helix.integration.task.TestEnqueueJobs)  Time elapsed: 900.006 s  <<< FAILURE!
2020-08-24T22:13:51.0336634Z org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testJobQueueAddingJobsAtSametime() didn't finish within the time-out 900000

>2020-08-24T20:59:27.7655449Z START testJobQueueAddingJobsAtSametime at Mon Aug 24 20:59:27 UTC 2020
2020-08-24T21:05:12.6335905Z 2657660 [Helix-RouterUpdater-event_process-TestZkCallbackHandlerLeak_testCurrentStatePathLeakingByAsycRemoval] ERROR org.apache.helix.spectator.RoutingTableProvider  - HelixManager is not connected for router update event: Event id : e9d13e16-0c33-42d9-8acc-838fe0078af4name:PeriodicalRebalance
2020-08-24T21:05:12.6337141Z changeContext:org.apache.helix.NotificationContext@1024f98a
2020-08-24T21:05:12.6337806Z helixmanager:org.apache.helix.integration.manager.ClusterSpectatorManager@2aca95c2
2020-08-24T21:05:12.6338296Z 
2020-08-24T21:05:12.6354077Z 2657662 [Helix-RouterUpdater-event_process-TestZkCallbackHandlerLeak_testCurrentStatePathLeakingByAsycRemoval] ERROR org.apache.helix.common.DedupEventProcessor  - Helix-RouterUpdater-event_process thread failed while running Helix-RouterUpdater-event_process
2020-08-24T21:05:12.6355158Z org.apache.helix.HelixException: HelixManager is not connected for router update event.
2020-08-24T21:05:12.6355871Z 	at org.apache.helix.spectator.RoutingTableProvider$RouterUpdater.handleEvent(RoutingTableProvider.java:891)
2020-08-24T21:05:12.6356738Z 	at org.apache.helix.spectator.RoutingTableProvider$RouterUpdater.handleEvent(RoutingTableProvider.java:855)
2020-08-24T21:05:12.6357940Z 	at org.apache.helix.common.DedupEventProcessor.run(DedupEventProcessor.java:61)
2020-08-24T21:06:06.9367152Z 2711964 [StatusDumpTimerTask] ERROR org.apache.helix.manager.zk.ZKHelixManager  - zkClient is not connected after waiting 10000ms., clusterName: TestCorrectnessOnConnectivityLoss_testParticipant, zkAddress: localhost:21892
2020-08-24T21:06:06.9379230Z ##[error]Exception in thread "StatusDumpTimerTask" org.apache.helix.HelixException: HelixManager is not connected within retry timeout for cluster TestCorrectnessOnConnectivityLoss_testParticipant
2020-08-24T21:06:06.9382326Z 	at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:402)
2020-08-24T21:06:06.9382472Z 	at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
2020-08-24T21:06:06.9382602Z 	at org.apache.helix.monitoring.ZKPathDataDumpTask.run(ZKPathDataDumpTask.java:69)
2020-08-24T21:06:06.9382724Z 	at java.util.TimerThread.mainLoop(Timer.java:555)
2020-08-24T21:06:06.9382849Z 	at java.util.TimerThread.run(Timer.java:505)
2020-08-24T21:06:09.6791536Z ##[error]Exception in thread "StatusDumpTimerTask" org.apache.helix.HelixException: HelixManager is not connected within retry timeout for cluster TestCorrectnessOnConnectivityLoss_testSpectator
2020-08-24T21:06:09.6794142Z 2714707 [StatusDumpTimerTask] ERROR org.apache.helix.manager.zk.ZKHelixManager  - zkClient is not connected after waiting 10000ms., clusterName: TestCorrectnessOnConnectivityLoss_testSpectator, zkAddress: localhost:21892
2020-08-24T21:06:09.6794573Z 	at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:402)
2020-08-24T21:06:09.6794849Z 	at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
2020-08-24T21:06:09.6795119Z 	at org.apache.helix.monitoring.ZKPathDataDumpTask.run(ZKPathDataDumpTask.java:69)
2020-08-24T21:06:09.6795373Z 	at java.util.TimerThread.mainLoop(Timer.java:555)
2020-08-24T21:06:09.6795620Z 	at java.util.TimerThread.run(Timer.java:505)
2020-08-24T21:10:12.6311954Z 2957660 [Helix-RouterUpdater-event_process-TestZkCallbackHandlerLeak_testCurrentStatePathLeakingByAsycRemoval] ERROR org.apache.helix.spectator.RoutingTableProvider  - HelixManager is not connected for router update event: Event id : 5470bda3-4b4f-4c1e-b063-588ae32f7209name:PeriodicalRebalance
2020-08-24T21:10:12.6313632Z changeContext:org.apache.helix.NotificationContext@1024f98a
2020-08-24T21:10:12.6314245Z helixmanager:org.apache.helix.integration.manager.ClusterSpectatorManager@2aca95c2
2020-08-24T21:10:12.6314709Z 
2020-08-24T21:10:12.6323292Z 2957660 [Helix-RouterUpdater-event_process-TestZkCallbackHandlerLeak_testCurrentStatePathLeakingByAsycRemoval] ERROR org.apache.helix.common.DedupEventProcessor  - Helix-RouterUpdater-event_process thread failed while running Helix-RouterUpdater-event_process
2020-08-24T21:10:12.6324842Z org.apache.helix.HelixException: HelixManager is not connected for router update event.
2020-08-24T21:10:12.6325342Z 	at org.apache.helix.spectator.RoutingTableProvider$RouterUpdater.handleEvent(RoutingTableProvider.java:891)
2020-08-24T21:10:12.6325667Z 	at org.apache.helix.spectator.RoutingTableProvider$RouterUpdater.handleEvent(RoutingTableProvider.java:855)
2020-08-24T21:10:12.6325940Z 	at org.apache.helix.common.DedupEventProcessor.run(DedupEventProcessor.java:61)
2020-08-24T21:14:27.7718960Z END testJobQueueAddingJobsAtSametime at Mon Aug 24 21:14:27 UTC 2020, took: 900005ms.

**Comment by kaisun2000** [comment]
#1346

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
