### ISSUE TITLE
fix TestQuotaBasedScheduling.testJobQueueScheduling

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1368]
LOG 951

> TestQuotaBasedScheduling.testJobQueueScheduling:555 expected:<5> but was:<4>

code

```
    for (int i = 5; i < 10; i++) {
      String jobName = "JOB_" + i;
      lastJobName = jobName;
      _driver.enqueueJob(queueName, jobName, jobConfigBulider);
    }
    _driver.resume(queueName);
    _driver.pollForJobState(queueName, queueName + "_" + lastJobName, TaskState.COMPLETED);

    // Check run counts for each quota type
    Assert.assertEquals((int) _quotaTypeExecutionCount.get("A"), 5);
    Assert.assertEquals((int) _quotaTypeExecutionCount.get("B"), 5);
    Assert.assertFalse(_quotaTypeExecutionCount.containsKey(DEFAULT_QUOTA_TYPE));
```

**Comment by kaisun2000** [comment]
#1365 

Is it the same root cause? @alirezazamani

**Comment by kaisun2000** [comment]
LOG 961

> 2020-09-17T07:10:31.8678311Z [ERROR] testJobQueueScheduling(org.apache.helix.integration.task.TestQuotaBasedScheduling)  Time elapsed: 1.124 s  <<< FAILURE!
2020-09-17T07:10:31.8684042Z java.lang.AssertionError: expected:<5> but was:<4>
2020-09-17T07:10:31.8694344Z 	at org.apache.helix.integration.task.TestQuotaBasedScheduling.testJobQueueScheduling(TestQuotaBasedScheduling.java:555)
2020-09-17T07:10:31.8697409Z 
2020-09-17T07:10:32.2675138Z [ERROR] Failures: 
2020-09-17T07:10:32.2678355Z [ERROR]   TestQuotaBasedScheduling.testJobQueueScheduling:555 expected:<5> but was:<4>

**Comment by kaisun2000** [comment]
LOG 958

>2020-09-17T06:16:23.0592050Z [ERROR] testJobQueueScheduling(org.apache.helix.integration.task.TestQuotaBasedScheduling)  Time elapsed: 0.679 s  <<< FAILURE!
2020-09-17T06:16:23.0594030Z java.lang.AssertionError: expected:<5> but was:<3>
2020-09-17T06:16:23.0596639Z 	at org.apache.helix.integration.task.TestQuotaBasedScheduling.testJobQueueScheduling(TestQuotaBasedScheduling.java:556)

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
