### ISSUE TITLE
fix TestJobTimeout.testTaskRunningIndefinitely

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1369]
LOG 920

> 2020-09-16T19:31:09.2223201Z [ERROR]   TestJobTimeout.testTaskRunningIndefinitely:107 expected:<TASK_ABORTED> but was:<null>

>2020-09-16T19:31:08.8191380Z [ERROR] testTaskRunningIndefinitely(org.apache.helix.integration.task.TestJobTimeout)  Time elapsed: 0.328 s  <<< FAILURE!
2020-09-16T19:31:08.8196465Z java.lang.AssertionError: expected:<TASK_ABORTED> but was:<null>
2020-09-16T19:31:08.8205281Z 	at org.apache.helix.integration.task.TestJobTimeout.testTaskRunningIndefinitely(TestJobTimeout.java:107)
2020-09-16T19:31:08.8208153Z

**Comment by kaisun2000** [comment]
This issue is separately reported by JJ and Huizhi

**Comment by kaisun2000** [comment]
LOG 1252
>2020-09-23T03:28:13.6540915Z [ERROR] testTaskRunningIndefinitely(org.apache.helix.integration.task.TestJobTimeout)  Time elapsed: 0.331 s  <<< FAILURE!
2020-09-23T03:28:13.6542875Z java.lang.AssertionError: expected:<TASK_ABORTED> but was:<null>
2020-09-23T03:28:13.6545099Z 	at org.apache.helix.integration.task.TestJobTimeout.testTaskRunningIndefinitely(TestJobTimeout.java:107)
2020-09-23T03:28:13.6546952Z

**Comment by kaisun2000** [comment]
1398

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
