### ISSUE TITLE
Have a better log message than exception stacktrace for routing data interval value being not set

### ISSUE THREAD

**Issue by narendly** [apache/helix#1370]
### Describe the bug
If routing data refresh interval is not set, something like this will be recorded

`java.lang.NumberFormatException: <LOG MESSAGE REDACTED DUE TO GDPR REQUIREMENTS>
	at java.lang.Long.parseLong(Long.java:552)
	at java.lang.Long.parseLong(Long.java:631)
	at org.apache.helix.zookeeper.impl.client.FederatedZkClient.getRoutingDataUpdateInterval(FederatedZkClient.java:643)
	at org.apache.helix.zookeeper.impl.client.FederatedZkClient.<init>(FederatedZkClient.java:107)
	at org.apache.helix.manager.zk.GenericZkHelixApiBuilder.createZkClient(GenericZkHelixApiBuilder.java:166)
	at org.apache.helix.tools.ClusterSetup$Builder.build(ClusterSetup.java:1631)
`

### To Reproduce
See the stacktrace.

### Expected behavior
Instead of logging the stacktrace, we could log a message.

### Additional context
N/A

**Comment by EverYoung124** [comment]
Why not detect environment is not set, then skip the parse?

**Comment by narendly** [comment]
@EverYoung124 That's also a valid solution. We'll consider that option at implementation time. Thanks for the input!
