### ISSUE TITLE
Fix TestTaskRebalancerStopResume.stopDeleteJobAndResumeNamedQueue

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1372]
LOG 976 touch 7

> 020-09-17T11:27:23.8512026Z [ERROR] stopDeleteJobAndResumeNamedQueue(org.apache.helix.integration.task.TestTaskRebalancerStopResume)  Time elapsed: 900.001 s  <<< FAILURE!
2020-09-17T11:27:23.8515885Z org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.stopDeleteJobAndResumeNamedQueue() didn't finish within the time-out 900000
2020-09-17T11:27:23.8519077Z

**Comment by kaisun2000** [comment]
similar to #1366

**Comment by kaisun2000** [comment]
LOG 979

>2020-09-17T11:29:48.0010235Z [ERROR] stopAndResumeNamedQueue(org.apache.helix.integration.task.TestTaskRebalancerStopResume)  Time elapsed: 900.013 s  <<< FAILURE!
2020-09-17T11:29:48.0022641Z org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.stopAndResumeNamedQueue() didn't finish within the time-out 900000
2020-09-17T11:29:48.0024922Z 
2020-09-17T11:29:48.3789290Z [ERROR] Failures: 
2020-09-17T11:29:48.3797170Z [ERROR]   TestTaskRebalancerStopResume.stopAndResumeNamedQueue » ThreadTimeout Method or...
2020-09-17T11:29:48.3798445Z [ERROR] Tests run: 1196, Failures: 1, Errors: 0, Skipped: 1

**Comment by kaisun2000** [comment]
LOG 1074 

>2020-09-19T01:20:52.9828081Z [ERROR] stopDeleteJobAndResumeNamedQueue(org.apache.helix.integration.task.TestTaskRebalancerStopResume)  Time elapsed: 607.514 s  <<< FAILURE!
2020-09-19T01:20:52.9839860Z org.apache.helix.HelixException: Workflow "stopDeleteJobAndResumeNamedQueue", job "stopDeleteJobAndResumeNamedQueue_slaveJob2_second" timed out
2020-09-19T01:20:52.9915658Z 	at org.apache.helix.integration.task.TestTaskRebalancerStopResume.stopDeleteJobAndResumeNamedQueue(TestTaskRebalancerStopResume.java:247)
2020-09-19T01:20:52.9919495Z 
2020-09-19T01:20:53.3830418Z [ERROR] Failures: 
2020-09-19T01:20:53.3836636Z [ERROR]   TestTaskRebalancerStopResume.stopDeleteJobAndResumeNamedQueue:247 » Helix Work...

**Comment by kaisun2000** [comment]
Note, this is a frequent failure case.

```

    // add job 3 back
    JobConfig.Builder job = new JobConfig.Builder().setCommand(MockTask.TASK_COMMAND)
        .setTargetResource(WorkflowGenerator.DEFAULT_TGT_DB)
        .setTargetPartitionStates(Sets.newHashSet("SLAVE"));

    // the name here MUST be unique in order to avoid conflicts with the old job cached in
    // RuntimeJobDag
    String newJob = deletedJob2 + "_second";
    LOG.info("Enqueuing job: " + newJob);
    _driver.enqueueJob(queueName, newJob, job);
    currentJobNames.add(newJob);

    // Ensure the jobs left are successful completed in the correct order
    long preJobFinish = 0;
    for (int i = 0; i < currentJobNames.size(); i++) {
      String namedSpaceJobName = String.format("%s_%s", queueName, currentJobNames.get(i));
      _driver.pollForJobState(queueName, namedSpaceJobName, TaskState.COMPLETED);    --------> failed here.

      JobContext jobContext = _driver.getJobContext(namedSpaceJobName);
      long jobStart = jobContext.getStartTime();
      Assert.assertTrue(jobStart >= preJobFinish);
      preJobFinish = jobContext.getFinishTime();
    }



```

**Comment by kaisun2000** [comment]
LOG 1252 09/22 touch 10 after JJ's rebalancer change

>2020-09-23T03:28:13.6548620Z [ERROR] stopDeleteJobAndResumeNamedQueue(org.apache.helix.integration.task.TestTaskRebalancerStopResume)  Time elapsed: 607.521 s  <<< FAILURE!
2020-09-23T03:28:13.6551573Z org.apache.helix.HelixException: Workflow "stopDeleteJobAndResumeNamedQueue", job "stopDeleteJobAndResumeNamedQueue_slaveJob2_second" timed out
2020-09-23T03:28:13.6555575Z 	at org.apache.helix.integration.task.TestTaskRebalancerStopResume.stopDeleteJobAndResumeNamedQueue(TestTaskRebalancerStopResume.java:247)
2020-09-23T03:28:13.6559777Z

**Comment by kaisun2000** [comment]
50 times single run with debug.

2000       JobConfig.Builder jobBuilder = new JobConfig.Builder().setCommand(MockTask.TASK_COMMAND)
          .setTargetResource(WorkflowGenerator.DEFAULT_TGT_DB)
          .setTargetPartitionStates(Sets.newHashSet(targetPartition))
          .setJobCommandConfigMap(Collections.singletonMap(MockTask.JOB_DELAY, "200"));
      String jobName = targetPartition.toLowerCase() + "Job" + i;
      LOG.info("Enqueuing job: " + jobName);
      queueBuilder.enqueueJob(jobName, jobBuilder);
      currentJobNames.add(i, jobName);

**Comment by kaisun2000** [comment]
adding job race condition avoid with pausing

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
