### ISSUE TITLE
Fix flaky TestPartitionMovementThrottle.testThrottleOnlyClusterLevelAnyType

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1386]
LOG 1198 09/21 touch 10

>2020-09-22T05:59:49.9201356Z [ERROR] testThrottleOnlyClusterLevelAnyType(org.apache.helix.integration.TestPartitionMovementThrottle)  Time elapsed: 307.109 s  <<< FAILURE!
2020-09-22T05:59:49.9203765Z java.lang.AssertionError: expected:< true > but was:< false >
2020-09-22T05:59:49.9207054Z 	at org.apache.helix.integration.TestPartitionMovementThrottle.testThrottleOnlyClusterLevelAnyType(TestPartitionMovementThrottle.java:279)
2020-09-22T05:59:49.9209669Z 
2020-09-22T05:59:50.3075469Z [ERROR] Failures: 
2020-09-22T05:59:50.3078306Z [ERROR]   TestPartitionMovementThrottle.testThrottleOnlyClusterLevelAnyType:279 expected:<true> but was:<false>

```
    ClusterLiveNodesVerifier liveNodesVerifier =
        new ClusterLiveNodesVerifier(_gZkClient, CLUSTER_NAME,
            Lists.transform(Arrays.asList(_participants), MockParticipantManager::getInstanceName));
    Assert.assertTrue(liveNodesVerifier.verifyByZkCallback(1000));
    Assert.assertTrue(_clusterVerifier.verifyByPolling());     ------> failing here


```

**Comment by kaisun2000** [comment]
> 2020-09-22T04:51:51.3027369Z START TestPartitionMovementThrottle testThrottleOnlyClusterLevelAnyType at Tue Sep 22 04:51:51 UTC 2020
2020-09-22T04:51:52.7377317Z 684549 [ZkClient-EventThread-16587-localhost:2183] ERROR org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks  - Interrupted waiting for success
2020-09-22T04:51:52.7379803Z java.lang.InterruptedException
2020-09-22T04:51:52.7380705Z 	at java.lang.Object.wait(Native Method)
2020-09-22T04:51:52.7381879Z 	at java.lang.Object.wait(Object.java:502)
2020-09-22T04:51:52.7383796Z 	at org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks$DefaultCallback.waitForSuccess(ZkAsyncCallbacks.java:220)
2020-09-22T04:51:52.7386296Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.issueSync(ZkClient.java:1305)
2020-09-22T04:51:52.7388179Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.access$300(ZkClient.java:83)
2020-09-22T04:51:52.7389907Z 	at org.apache.helix.zookeeper.zkclient.ZkClient$4.run(ZkClient.java:1331)
2020-09-22T04:51:52.7391694Z 	at org.apache.helix.zookeeper.zkclient.ZkEventThread.run(ZkEventThread.java:99)
2020-09-22T04:51:55.0892669Z no throttle result for :localhost_12920
2020-09-22T04:51:55.0893819Z no throttle result for :localhost_12921
2020-09-22T04:51:55.0894538Z no throttle result for :localhost_12922
2020-09-22T04:51:55.4739163Z 687286 [HelixController-pipeline-default-CLUSTER_TestPartitionMovementThrottle-(376b0c57_DEFAULT)] ERROR org.apache.helix.controller.stages.StateTransitionThrottleController  - Wrong rebalance type NONE as parameter
2020-09-22T04:51:55.4744365Z 687286 [HelixController-pipeline-default-CLUSTER_TestPartitionMovementThrottle-(376b0c57_DEFAULT)] ERROR org.apache.helix.controller.stages.StateTransitionThrottleController  - Wrong rebalance type NONE as parameter
2020-09-22T04:51:55.4749250Z 687286 [HelixController-pipeline-default-CLUSTER_TestPartitionMovementThrottle-(376b0c57_DEFAULT)] ERROR org.apache.helix.controller.stages.StateTransitionThrottleController  - Wrong rebalance type NONE as parameter
2020-09-22T04:51:57.2169181Z 689028 [ZkClient-EventThread-16705-localhost:2183] ERROR org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks  - Interrupted waiting for success
2020-09-22T04:51:57.2171993Z java.lang.InterruptedException
2020-09-22T04:51:57.2172944Z 	at java.lang.Object.wait(Native Method)
2020-09-22T04:51:57.2173739Z 	at java.lang.Object.wait(Object.java:502)
2020-09-22T04:51:57.2176576Z 	at org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks$DefaultCallback.waitForSuccess(ZkAsyncCallbacks.java:220)
2020-09-22T04:51:57.2179129Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.issueSync(ZkClient.java:1305)
2020-09-22T04:51:57.2180788Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.access$300(ZkClient.java:83)
2020-09-22T04:51:57.2182218Z 	at org.apache.helix.zookeeper.zkclient.ZkClient$4.run(ZkClient.java:1331)
2020-09-22T04:51:57.2186712Z 	at org.apache.helix.zookeeper.zkclient.ZkEventThread.run(ZkEventThread.java:99)
2020-09-22T04:51:57.4695312Z 689280 [HelixController-pipeline-default-CLUSTER_TestPartitionMovementThrottle-(d87b3a25_DEFAULT)] ERROR org.apache.helix.controller.stages.StateTransitionThrottleController  - Wrong rebalance type NONE as parameter
2020-09-22T04:51:57.4700583Z 689280 [HelixController-pipeline-default-CLUSTER_TestPartitionMovementThrottle-(d87b3a25_DEFAULT)] ERROR org.apache.helix.controller.stages.StateTransitionThrottleController  - Wrong rebalance type NONE as parameter
2020-09-22T04:51:57.4705634Z 689280 [HelixController-pipeline-default-CLUSTER_TestPartitionMovementThrottle-(d87b3a25_DEFAULT)] ERROR org.apache.helix.controller.stages.StateTransitionThrottleController  - Wrong rebalance type NONE as parameter
2020-09-22T04:51:58.6586935Z 690469 [HelixController-pipeline-default-CLUSTER_TestPartitionMovementThrottle-(f0bd536a_DEFAULT)] ERROR org.apache.helix.controller.stages.StateTransitionThrottleController  - Wrong rebalance type NONE as parameter
2020-09-22T04:51:58.6592355Z 690469 [HelixController-pipeline-default-CLUSTER_TestPartitionMovementThrottle-(f0bd536a_DEFAULT)] ERROR org.apache.helix.controller.stages.StateTransitionThrottleController  - Wrong rebalance type NONE as parameter
2020-09-22T04:51:58.6597249Z 690469 [HelixController-pipeline-default-CLUSTER_TestPartitionMovementThrottle-(f0bd536a_DEFAULT)] ERROR org.apache.helix.controller.stages.StateTransitionThrottleController  - Wrong rebalance type NONE as parameter
2020-09-22T04:51:59.7540974Z 691565 [ZkClient-EventThread-16742-localhost:2183] ERROR org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks  - Interrupted waiting for success

**Comment by kaisun2000** [comment]
```
      StateTransitionThrottleConfig.RebalanceType rebalanceType = RebalanceType.NONE;
      if (partitionsNeedRecovery.contains(partition)) {
        rebalanceType = StateTransitionThrottleConfig.RebalanceType.RECOVERY_BALANCE;
      } else if (partitionsNeedLoadbalance.contains(partition)) {
        rebalanceType = StateTransitionThrottleConfig.RebalanceType.LOAD_BALANCE;
      }
-----> NONE can be passed in. Is it a problem ?
      if (pendingMap.size() > 0) {
        boolean shouldChargePartition = false;
        for (String instance : pendingMap.keySet()) {
          String currentState = currentStateMap.get(instance);
          String pendingState = pendingMap.get(instance);
          if (pendingState != null && !pendingState.equals(currentState)
              && !cache.getDisabledInstancesForPartition(resourceName, partition.getPartitionName())
              .contains(instance)) {
            // Only charge this instance if the partition is not disabled
            throttleController.chargeInstance(rebalanceType, instance);
            shouldChargePartition = true;
            // If there is a pending state transition for the partition, that means that an assignment
            // has already been made and the state transition message has already been sent out for the partition
            // in a previous pipeline run. We must honor this and reflect it by charging for the pending state transition message.

            // Since the assignment has already been made for the pending message, we do a special treatment
            // for it by setting the best possible state directly in intermediatePartitionStateMap so that the pending
            // message won't be double-assigned or double-charged in recovery or load balance.
            handlePendingStateTransitionsForThrottling(partition, partitionsNeedRecovery,
                partitionsNeedLoadbalance, rebalanceType, bestPossiblePartitionStateMap,
                intermediatePartitionStateMap);
          }
        }
        if (shouldChargePartition) {
          throttleController.chargeCluster(rebalanceType);
          throttleController.chargeResource(rebalanceType, resourceName);
        }
      }
    }
  }

```

**Comment by kaisun2000** [comment]
No need to do final bestpossible verify

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
