### ISSUE TITLE
Error job null logs polluting test run in helix rest

### ISSUE THREAD

**Issue by huizhilu** [apache/helix#1391]
### How to reproduce
build and run tests in `helix-rest` module.

```
ob_1
5    [HelixController-pipeline-task-TestCluster_0-(8ceb38b8_TASK)] ERROR org.apache.helix.task.AbstractTaskDispatcher  - The job config is missing for job Workflow_1_Job_2
73   [HelixController-pipeline-task-TestCluster_0-(2e927519_TASK)] ERROR org.apache.helix.task.JobDispatcher  - Job configuration is NULL for Workflow_0_Job_2
73   [HelixController-pipeline-task-TestCluster_0-(2e927519_TASK)] ERROR org.apache.helix.task.JobDispatcher  - Job configuration is NULL for Workflow_0_Job_1
75   [HelixController-pipeline-task-TestCluster_0-(2e927519_TASK)] ERROR org.apache.helix.task.JobDispatcher  - Job configuration is NULL for Workflow_0_Job_0
75   [HelixController-pipeline-task-TestCluster_0-(2e927519_TASK)] ERROR org.apache.helix.task.JobDispatcher  - Job configuration is NULL for Workflow_2_Job_1
75   [HelixController-pipeline-task-TestCluster_0-(2e927519_TASK)] ERROR org.apache.helix.task.JobDispatcher  - Job configuration is NULL for Workflow_2_Job_2
```

**Comment by pkuwm** [comment]
@alirezazamani Can you help take a look at this? I believe you enabled the error log before. How about down level it to `WARN`? Is the log critical?

**Comment by pkuwm** [comment]
Waged metrics related log in helix-rest.

```
18816 [HelixController-pipeline-default-TestCluster_0-(f7860f7e_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.waged.WagedRebalancer  - Failed to calculate the new assignments.
org.apache.helix.HelixRebalanceException: Failed to generate cluster model for global rebalance. Failure Type: INVALID_CLUSTER_STATUS
	at org.apache.helix.controller.rebalancer.waged.WagedRebalancer.globalRebalance(WagedRebalancer.java:427)
	at org.apache.helix.controller.rebalancer.waged.WagedRebalancer.computeBestPossibleAssignment(WagedRebalancer.java:354)
	at org.apache.helix.controller.rebalancer.waged.WagedRebalancer.computeBestPossibleStates(WagedRebalancer.java:327)
	at org.apache.helix.controller.rebalancer.waged.WagedRebalancer.computeNewIdealStates(WagedRebalancer.java:262)
	at org.apache.helix.controller.stages.BestPossibleStateCalcStage.computeResourceBestPossibleStateWithWagedRebalancer(BestPossibleStateCalcStage.java:270)
	at org.apache.helix.controller.stages.BestPossibleStateCalcStage.compute(BestPossibleStateCalcStage.java:126)
	at org.apache.helix.controller.stages.BestPossibleStateCalcStage.process(BestPossibleStateCalcStage.java:85)
	at org.apache.helix.controller.pipeline.Pipeline.handle(Pipeline.java:68)
	at org.apache.helix.controller.GenericHelixController.handleEvent(GenericHelixController.java:777)
	at org.apache.helix.controller.GenericHelixController.access$500(GenericHelixController.java:128)
	at org.apache.helix.controller.GenericHelixController$ClusterEventProcessor.run(GenericHelixController.java:1407)
Caused by: org.apache.helix.HelixException: The required capacity keys: [FOO, BAR] are not fully configured in the resource: TestCluster_0_db_0, partition: TestCluster_0_db_0_0, weight map: {}.
	at org.apache.helix.controller.rebalancer.util.WagedValidationUtil.validateAndGetPartitionCapacity(WagedValidationUtil.java:84)
	at org.apache.helix.controller.rebalancer.waged.model.AssignableReplica.fetchCapacityUsage(AssignableReplica.java:156)
	at org.apache.helix.controller.rebalancer.waged.model.AssignableReplica.<init>(AssignableReplica.java:65)
	at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.lambda$getAllAssignableReplicas$14(ClusterModelProvider.java:483)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
	at java.util.stream.AbstractTask.compute(AbstractTask.java:316)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870)
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467)
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.getAllAssignableReplicas(ClusterModelProvider.java:488)
	at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModel(ClusterModelProvider.java:147)
	at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModelForBaseline(ClusterModelProvider.java:97)
	at org.apache.helix.controller.rebalancer.waged.WagedRebalancer.globalRebalance(WagedRebalancer.java:424)
	... 10 more
```
