### ISSUE TITLE
fix TestControllerLiveLock.test

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1392]
Since the use of DelayedRebalancer as default from JJ this one is not stable

>2020-09-23T03:28:13.6527533Z [ERROR] test(org.apache.helix.integration.controller.TestControllerLiveLock)  Time elapsed: 42.874 s  <<< FAILURE!
2020-09-23T03:28:13.6530302Z java.lang.AssertionError: expected:<true> but was:<false>
2020-09-23T03:28:13.6537988Z 	at org.apache.helix.integration.controller.TestControllerLiveLock.test(TestControllerLiveLock.java:91)
2020-09-23T03:28:13.6539693Z

**Comment by kaisun2000** [comment]
{
  "id" : "TestDB0",
  "simpleFields" : {
    "IDEAL_STATE_MODE" : "AUTO_REBALANCE",
    "NUM_PARTITIONS" : "256",
    "REBALANCE_MODE" : "FULL_AUTO",
    "REBALANCE_STRATEGY" : "DEFAULT",
    "REPLICAS" : "1",
    "STATE_MODEL_DEF_REF" : "LeaderStandby",
    "STATE_MODEL_FACTORY_NAME" : "DEFAULT"
  },
  "mapFields" : {
    "TestDB0_0" : { },
    "TestDB0_1" : { },
    "TestDB0_10" : { },
    "TestDB0_100" : { },
    "TestDB0_101" : { },
    "TestDB0_102" : { },
    "TestDB0_103" : { },
    "TestDB0_104" : { },
    "TestDB0_105" : { },
    "TestDB0_106" : { },
    "TestDB0_107" : { },
    "TestDB0_108" : { },
    "TestDB0_109" : { },
    "TestDB0_11" : { },
    "TestDB0_110" : { },
    "TestDB0_111" : { },
    "TestDB0_112" : { },
    "TestDB0_113" : { },
    "TestDB0_114" : { },
    "TestDB0_115" : { },
    "TestDB0_116" : { },
    "TestDB0_117" : { },
    "TestDB0_118" : { },
    "TestDB0_119" : { },
    "TestDB0_12" : { },
    "TestDB0_120" : { },
    "TestDB0_121" : { },
    "TestDB0_122" : { },
    "TestDB0_123" : { },
    "TestDB0_124" : { },
    "TestDB0_125" : { },
    "TestDB0_126" : { },
    "TestDB0_127" : { },
    "TestDB0_128" : { },
    "TestDB0_129" : { },
    "TestDB0_13" : { },
    "TestDB0_130" : { },
    "TestDB0_131" : { },
    "TestDB0_132" : { },
    "TestDB0_133" : { },
    "TestDB0_134" : { },
    "TestDB0_135" : { },
    "TestDB0_136" : { },
    "TestDB0_137" : { },
    "TestDB0_138" : { },
    "TestDB0_139" : { },
    "TestDB0_14" : { },
    "TestDB0_140" : { },
    "TestDB0_141" : { },
    "TestDB0_142" : { },
    "TestDB0_143" : { },
    "TestDB0_144" : { },
    "TestDB0_145" : { },
    "TestDB0_146" : { },
    "TestDB0_147" : { },
    "TestDB0_148" : { },
    "TestDB0_149" : { },
    "TestDB0_15" : { },
    "TestDB0_150" : { },
    "TestDB0_151" : { },
    "TestDB0_152" : { },
    "TestDB0_153" : { },
    "TestDB0_154" : { },
    "TestDB0_155" : { },
    "TestDB0_156" : { },
    "TestDB0_157" : { },
    "TestDB0_158" : { },
    "TestDB0_159" : { },
    "TestDB0_16" : { },
    "TestDB0_160" : { },
    "TestDB0_161" : { },
    "TestDB0_162" : { },
    "TestDB0_163" : { },
    "TestDB0_164" : { },
    "TestDB0_165" : { },
    "TestDB0_166" : { },
    "TestDB0_167" : { },
    "TestDB0_168" : { },
    "TestDB0_169" : { },
    "TestDB0_17" : { },
    "TestDB0_170" : { },
    "TestDB0_171" : { },
    "TestDB0_172" : { },
    "TestDB0_173" : { },
    "TestDB0_174" : { },
    "TestDB0_175" : { },
    "TestDB0_176" : { },
    "TestDB0_177" : { },
    "TestDB0_178" : { },
    "TestDB0_179" : { },
    "TestDB0_18" : { },
    "TestDB0_180" : { },
    "TestDB0_181" : { },
    "TestDB0_182" : { },
    "TestDB0_183" : { },
    "TestDB0_184" : { },
    "TestDB0_185" : { },
    "TestDB0_186" : { },
    "TestDB0_187" : { },
    "TestDB0_188" : { },
    "TestDB0_189" : { },
    "TestDB0_19" : { },
    "TestDB0_190" : { },
    "TestDB0_191" : { },
    "TestDB0_192" : { },
    "TestDB0_193" : { },
    "TestDB0_194" : { },
    "TestDB0_195" : { },
    "TestDB0_196" : { },
    "TestDB0_197" : { },
    "TestDB0_198" : { },
    "TestDB0_199" : { },
    "TestDB0_2" : { },
    "TestDB0_20" : { },
    "TestDB0_200" : { },
    "TestDB0_201" : { },
    "TestDB0_202" : { },
    "TestDB0_203" : { },
    "TestDB0_204" : { },
    "TestDB0_205" : { },
    "TestDB0_206" : { },
    "TestDB0_207" : { },
    "TestDB0_208" : { },
    "TestDB0_209" : { },
    "TestDB0_21" : { },
    "TestDB0_210" : { },
    "TestDB0_211" : { },
    "TestDB0_212" : { },
    "TestDB0_213" : { },
    "TestDB0_214" : { },
    "TestDB0_215" : { },
    "TestDB0_216" : { },
    "TestDB0_217" : { },
    "TestDB0_218" : { },
    "TestDB0_219" : { },
    "TestDB0_22" : { },
    "TestDB0_220" : { },
    "TestDB0_221" : { },
    "TestDB0_222" : { },
    "TestDB0_223" : { },
    "TestDB0_224" : { },
    "TestDB0_225" : { },
    "TestDB0_226" : { },
    "TestDB0_227" : { },
    "TestDB0_228" : { },
    "TestDB0_229" : { },
    "TestDB0_23" : { },
    "TestDB0_230" : { },
    "TestDB0_231" : { },
    "TestDB0_232" : { },
    "TestDB0_233" : { },
    "TestDB0_234" : { },
    "TestDB0_235" : { },
    "TestDB0_236" : { },
    "TestDB0_237" : { },
    "TestDB0_238" : { },
    "TestDB0_239" : { },
    "TestDB0_24" : { },
    "TestDB0_240" : { },
    "TestDB0_241" : { },
    "TestDB0_242" : { },
    "TestDB0_243" : { },
    "TestDB0_244" : { },
    "TestDB0_245" : { },
    "TestDB0_246" : { },
    "TestDB0_247" : { },
    "TestDB0_248" : { },
    "TestDB0_249" : { },
    "TestDB0_25" : { },
    "TestDB0_250" : { },
    "TestDB0_251" : { },
    "TestDB0_252" : { },
    "TestDB0_253" : { },
    "TestDB0_254" : { },
    "TestDB0_255" : { },
    "TestDB0_26" : { },
    "TestDB0_27" : { },
    "TestDB0_28" : { },
    "TestDB0_29" : { },
    "TestDB0_3" : { },
    "TestDB0_30" : { },
    "TestDB0_31" : { },
    "TestDB0_32" : { },
    "TestDB0_33" : { },
    "TestDB0_34" : { },
    "TestDB0_35" : { },
    "TestDB0_36" : { },
    "TestDB0_37" : { },
    "TestDB0_38" : { },
    "TestDB0_39" : { },
    "TestDB0_4" : { },
    "TestDB0_40" : { },
    "TestDB0_41" : { },
    "TestDB0_42" : { },
    "TestDB0_43" : { },
    "TestDB0_44" : { },
    "TestDB0_45" : { },
    "TestDB0_46" : { },
    "TestDB0_47" : { },
    "TestDB0_48" : { },
    "TestDB0_49" : { },
    "TestDB0_5" : { },
    "TestDB0_50" : { },
    "TestDB0_51" : { },
    "TestDB0_52" : { },
    "TestDB0_53" : { },
    "TestDB0_54" : { },
    "TestDB0_55" : { },
    "TestDB0_56" : { },
    "TestDB0_57" : { },
    "TestDB0_58" : { },
    "TestDB0_59" : { },
    "TestDB0_6" : { },
    "TestDB0_60" : { },
    "TestDB0_61" : { },
    "TestDB0_62" : { },
    "TestDB0_63" : { },
    "TestDB0_64" : { },
    "TestDB0_65" : { },
    "TestDB0_66" : { },
    "TestDB0_67" : { },
    "TestDB0_68" : { },
    "TestDB0_69" : { },
    "TestDB0_7" : { },
    "TestDB0_70" : { },
    "TestDB0_71" : { },
    "TestDB0_72" : { },
    "TestDB0_73" : { },
    "TestDB0_74" : { },
    "TestDB0_75" : { },
    "TestDB0_76" : { },
    "TestDB0_77" : { },
    "TestDB0_78" : { },
    "TestDB0_79" : { },
    "TestDB0_8" : { },
    "TestDB0_80" : { },
    "TestDB0_81" : { },
    "TestDB0_82" : { },
    "TestDB0_83" : { },
    "TestDB0_84" : { },
    "TestDB0_85" : { },
    "TestDB0_86" : { },
    "TestDB0_87" : { },
    "TestDB0_88" : { },
    "TestDB0_89" : { },
    "TestDB0_9" : { },
    "TestDB0_90" : { },
    "TestDB0_91" : { },
    "TestDB0_92" : { },
    "TestDB0_93" : { },
    "TestDB0_94" : { },
    "TestDB0_95" : { },
    "TestDB0_96" : { },
    "TestDB0_97" : { },
    "TestDB0_98" : { },
    "TestDB0_99" : { }
  },
  "listFields" : {
    "TestDB0_0" : [ ],
    "TestDB0_1" : [ ],
    "TestDB0_10" : [ ],
    "TestDB0_100" : [ ],
    "TestDB0_101" : [ ],
    "TestDB0_102" : [ ],
    "TestDB0_103" : [ ],
    "TestDB0_104" : [ ],
    "TestDB0_105" : [ ],
    "TestDB0_106" : [ ],
    "TestDB0_107" : [ ],
    "TestDB0_108" : [ ],
    "TestDB0_109" : [ ],
    "TestDB0_11" : [ ],
    "TestDB0_110" : [ ],
    "TestDB0_111" : [ ],
    "TestDB0_112" : [ ],
    "TestDB0_113" : [ ],
    "TestDB0_114" : [ ],
    "TestDB0_115" : [ ],
    "TestDB0_116" : [ ],
    "TestDB0_117" : [ ],
    "TestDB0_118" : [ ],
    "TestDB0_119" : [ ],
    "TestDB0_12" : [ ],
    "TestDB0_120" : [ ],
    "TestDB0_121" : [ ],
    "TestDB0_122" : [ ],
    "TestDB0_123" : [ ],
    "TestDB0_124" : [ ],
    "TestDB0_125" : [ ],
    "TestDB0_126" : [ ],
    "TestDB0_127" : [ ],
    "TestDB0_128" : [ ],
    "TestDB0_129" : [ ],
    "TestDB0_13" : [ ],
    "TestDB0_130" : [ ],
    "TestDB0_131" : [ ],
    "TestDB0_132" : [ ],
    "TestDB0_133" : [ ],
    "TestDB0_134" : [ ],
    "TestDB0_135" : [ ],
    "TestDB0_136" : [ ],
    "TestDB0_137" : [ ],
    "TestDB0_138" : [ ],
    "TestDB0_139" : [ ],
    "TestDB0_14" : [ ],
    "TestDB0_140" : [ ],
    "TestDB0_141" : [ ],
    "TestDB0_142" : [ ],
    "TestDB0_143" : [ ],
    "TestDB0_144" : [ ],
    "TestDB0_145" : [ ],
    "TestDB0_146" : [ ],
    "TestDB0_147" : [ ],
    "TestDB0_148" : [ ],
    "TestDB0_149" : [ ],
    "TestDB0_15" : [ ],
    "TestDB0_150" : [ ],
    "TestDB0_151" : [ ],
    "TestDB0_152" : [ ],
    "TestDB0_153" : [ ],
    "TestDB0_154" : [ ],
    "TestDB0_155" : [ ],
    "TestDB0_156" : [ ],
    "TestDB0_157" : [ ],
    "TestDB0_158" : [ ],
    "TestDB0_159" : [ ],
    "TestDB0_16" : [ ],
    "TestDB0_160" : [ ],
    "TestDB0_161" : [ ],
    "TestDB0_162" : [ ],
    "TestDB0_163" : [ ],
    "TestDB0_164" : [ ],
    "TestDB0_165" : [ ],
    "TestDB0_166" : [ ],
    "TestDB0_167" : [ ],
    "TestDB0_168" : [ ],
    "TestDB0_169" : [ ],
    "TestDB0_17" : [ ],
    "TestDB0_170" : [ ],
    "TestDB0_171" : [ ],
    "TestDB0_172" : [ ],
    "TestDB0_173" : [ ],
    "TestDB0_174" : [ ],
    "TestDB0_175" : [ ],
    "TestDB0_176" : [ ],
    "TestDB0_177" : [ ],
    "TestDB0_178" : [ ],
    "TestDB0_179" : [ ],
    "TestDB0_18" : [ ],
    "TestDB0_180" : [ ],
    "TestDB0_181" : [ ],
    "TestDB0_182" : [ ],
    "TestDB0_183" : [ ],
    "TestDB0_184" : [ ],
    "TestDB0_185" : [ ],
    "TestDB0_186" : [ ],
    "TestDB0_187" : [ ],
    "TestDB0_188" : [ ],
    "TestDB0_189" : [ ],
    "TestDB0_19" : [ ],
    "TestDB0_190" : [ ],
    "TestDB0_191" : [ ],
    "TestDB0_192" : [ ],
    "TestDB0_193" : [ ],
    "TestDB0_194" : [ ],
    "TestDB0_195" : [ ],
    "TestDB0_196" : [ ],
    "TestDB0_197" : [ ],
    "TestDB0_198" : [ ],
    "TestDB0_199" : [ ],
    "TestDB0_2" : [ ],
    "TestDB0_20" : [ ],
    "TestDB0_200" : [ ],
    "TestDB0_201" : [ ],
    "TestDB0_202" : [ ],
    "TestDB0_203" : [ ],
    "TestDB0_204" : [ ],
    "TestDB0_205" : [ ],
    "TestDB0_206" : [ ],
    "TestDB0_207" : [ ],
    "TestDB0_208" : [ ],
    "TestDB0_209" : [ ],
    "TestDB0_21" : [ ],
    "TestDB0_210" : [ ],
    "TestDB0_211" : [ ],
    "TestDB0_212" : [ ],
    "TestDB0_213" : [ ],
    "TestDB0_214" : [ ],
    "TestDB0_215" : [ ],
    "TestDB0_216" : [ ],
    "TestDB0_217" : [ ],
    "TestDB0_218" : [ ],
    "TestDB0_219" : [ ],
    "TestDB0_22" : [ ],
    "TestDB0_220" : [ ],
    "TestDB0_221" : [ ],
    "TestDB0_222" : [ ],
    "TestDB0_223" : [ ],
    "TestDB0_224" : [ ],
    "TestDB0_225" : [ ],
    "TestDB0_226" : [ ],
    "TestDB0_227" : [ ],
    "TestDB0_228" : [ ],
    "TestDB0_229" : [ ],
    "TestDB0_23" : [ ],
    "TestDB0_230" : [ ],
    "TestDB0_231" : [ ],
    "TestDB0_232" : [ ],
    "TestDB0_233" : [ ],
    "TestDB0_234" : [ ],
    "TestDB0_235" : [ ],
    "TestDB0_236" : [ ],
    "TestDB0_237" : [ ],
    "TestDB0_238" : [ ],
    "TestDB0_239" : [ ],
    "TestDB0_24" : [ ],
    "TestDB0_240" : [ ],
    "TestDB0_241" : [ ],
    "TestDB0_242" : [ ],
    "TestDB0_243" : [ ],
    "TestDB0_244" : [ ],
    "TestDB0_245" : [ ],
    "TestDB0_246" : [ ],
    "TestDB0_247" : [ ],
    "TestDB0_248" : [ ],
    "TestDB0_249" : [ ],
    "TestDB0_25" : [ ],
    "TestDB0_250" : [ ],
    "TestDB0_251" : [ ],
    "TestDB0_252" : [ ],
    "TestDB0_253" : [ ],
    "TestDB0_254" : [ ],
    "TestDB0_255" : [ ],
    "TestDB0_26" : [ ],
    "TestDB0_27" : [ ],
    "TestDB0_28" : [ ],
    "TestDB0_29" : [ ],
    "TestDB0_3" : [ ],
    "TestDB0_30" : [ ],
    "TestDB0_31" : [ ],
    "TestDB0_32" : [ ],
    "TestDB0_33" : [ ],
    "TestDB0_34" : [ ],
    "TestDB0_35" : [ ],
    "TestDB0_36" : [ ],
    "TestDB0_37" : [ ],
    "TestDB0_38" : [ ],
    "TestDB0_39" : [ ],
    "TestDB0_4" : [ ],
    "TestDB0_40" : [ ],
    "TestDB0_41" : [ ],
    "TestDB0_42" : [ ],
    "TestDB0_43" : [ ],
    "TestDB0_44" : [ ],
    "TestDB0_45" : [ ],
    "TestDB0_46" : [ ],
    "TestDB0_47" : [ ],
    "TestDB0_48" : [ ],
    "TestDB0_49" : [ ],
    "TestDB0_5" : [ ],
    "TestDB0_50" : [ ],
    "TestDB0_51" : [ ],
    "TestDB0_52" : [ ],
    "TestDB0_53" : [ ],
    "TestDB0_54" : [ ],
    "TestDB0_55" : [ ],
    "TestDB0_56" : [ ],
    "TestDB0_57" : [ ],
    "TestDB0_58" : [ ],
    "TestDB0_59" : [ ],
    "TestDB0_6" : [ ],
    "TestDB0_60" : [ ],
    "TestDB0_61" : [ ],
    "TestDB0_62" : [ ],
    "TestDB0_63" : [ ],
    "TestDB0_64" : [ ],
    "TestDB0_65" : [ ],
    "TestDB0_66" : [ ],
    "TestDB0_67" : [ ],
    "TestDB0_68" : [ ],
    "TestDB0_69" : [ ],
    "TestDB0_7" : [ ],
    "TestDB0_70" : [ ],
    "TestDB0_71" : [ ],
    "TestDB0_72" : [ ],
    "TestDB0_73" : [ ],
    "TestDB0_74" : [ ],
    "TestDB0_75" : [ ],
    "TestDB0_76" : [ ],
    "TestDB0_77" : [ ],
    "TestDB0_78" : [ ],
    "TestDB0_79" : [ ],
    "TestDB0_8" : [ ],
    "TestDB0_80" : [ ],
    "TestDB0_81" : [ ],
    "TestDB0_82" : [ ],
    "TestDB0_83" : [ ],
    "TestDB0_84" : [ ],
    "TestDB0_85" : [ ],
    "TestDB0_86" : [ ],
    "TestDB0_87" : [ ],
    "TestDB0_88" : [ ],
    "TestDB0_89" : [ ],
    "TestDB0_9" : [ ],
    "TestDB0_90" : [ ],
    "TestDB0_91" : [ ],
    "TestDB0_92" : [ ],
    "TestDB0_93" : [ ],
    "TestDB0_94" : [ ],
    "TestDB0_95" : [ ],
    "TestDB0_96" : [ ],
    "TestDB0_97" : [ ],
    "TestDB0_98" : [ ],
    "TestDB0_99" : [ ]
  }
}

**Comment by kaisun2000** [comment]
LOG 1250
>2020-09-23T03:18:05.5036929Z [ERROR] test(org.apache.helix.integration.controller.TestControllerLiveLock)  Time elapsed: 40.744 s  <<< FAILURE!
2020-09-23T03:18:05.5040884Z java.lang.AssertionError: expected:<true> but was:<false>
2020-09-23T03:18:05.5046238Z 	at org.apache.helix.integration.controller.TestControllerLiveLock.test(TestControllerLiveLock.java:91)
2020-09-23T03:18:05.5047765Z 
2020-09-23T03:18:05.9146727Z [ERROR] Failures: 
2020-09-23T03:18:05.9150902Z [ERROR]   TestControllerLiveLock.test:91 expected:<true> but was:<false>
2020-09-23T03:18:05.9160512Z [ERROR] Tests run: 1196, Failures: 1, Errors: 0, Skipped: 1

**Comment by kaisun2000** [comment]
2020-09-23T05:29:28.6492530Z 2436904 [HelixController-pipeline-default-TestControllerLiveLock_test-(19097af4_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer  - No instances or active instances available for resource TestDB0, allInstances: [localhost_12919, localhost_12926, localhost_12927, localhost_12928, localhost_12929, localhost_12918, localhost_12922, localhost_12923, localhost_12924, localhost_12925, localhost_12920, localhost_12921], liveInstances: [], activeInstances: []

**Comment by kaisun2000** [comment]
start up controller later would be eliminate the above error message

**Comment by kaisun2000** [comment]
The gist is that using DelayedAutoRebalancer with AutoRebalanceStrategy together, it BestPossibleVerifier may never converge.

As discussed with JJ, need to change this one use have DelayedAutoRebalancer with CrushED

**Comment by kaisun2000** [comment]
Note, the fix from #1401 changed to setup cluster to use CrushED if mode is full-auto
