### ISSUE TITLE
fix TestHelixAdminCli.testInstanceOperations

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1395]
https://pipelines.actions.githubusercontent.com/sLVPVVo6suizPM5gIrHDigmaxapcQ7bGBvxdUFsAfGjAfNkqWG/_apis/pipelines/1/runs/1245/signedlogcontent/3?urlExpires=2020-09-23T05%3A48%3A16.7724804Z&urlSigningMethod=HMACV1&urlSignature=KZJalkD%2FdS9qFB%2FawetmC4bXgCN3vF1JBgEnUjsVgJk%3D

>2020-09-23T03:17:57.5660415Z [ERROR] testInstanceOperations(org.apache.helix.tools.TestHelixAdminCli)  Time elapsed: 6.465 s  <<< FAILURE!
2020-09-23T03:17:57.5662151Z org.apache.helix.HelixException: Failed to drop instance: localhost_1232. Retry times: 3
2020-09-23T03:17:57.5664154Z 	at org.apache.helix.tools.TestHelixAdminCli.testInstanceOperations(TestHelixAdminCli.java:469)
2020-09-23T03:17:57.5666733Z Caused by: org.apache.helix.zookeeper.exception.ZkClientException: Failed to delete /TestHelixAdminCli/INSTANCES/localhost_1232/MESSAGES
2020-09-23T03:17:57.5669287Z 	at org.apache.helix.tools.TestHelixAdminCli.testInstanceOperations(TestHelixAdminCli.java:469)
2020-09-23T03:17:57.5672756Z Caused by: org.apache.helix.zookeeper.zkclient.exception.ZkException: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /TestHelixAdminCli/INSTANCES/localhost_1232/MESSAGES
2020-09-23T03:17:57.5676063Z 	at org.apache.helix.tools.TestHelixAdminCli.testInstanceOperations(TestHelixAdminCli.java:469)
2020-09-23T03:17:57.5678491Z Caused by: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /TestHelixAdminCli/INSTANCES/localhost_1232/MESSAGES
2020-09-23T03:17:57.5684204Z 	at org.apache.helix.tools.TestHelixAdminCli.testInstanceOperations(TestHelixAdminCli.java:469)
2020-09-23T03:17:57.5685464Z 
2020-09-23T03:17:57.9568969Z [ERROR] Failures: 
2020-09-23T03:17:57.9571118Z [ERROR]   TestHelixAdminCli.testInstanceOperations:469 » Helix Failed to drop instance: ...

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
