### ISSUE TITLE
fix TestDeleteJobFromJobQueue.testForceDeleteJobFromJobQueue

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1406]
LOG 1431

>2020-09-25T01:00:23.5925462Z [ERROR] testForceDeleteJobFromJobQueue(org.apache.helix.integration.task.TestDeleteJobFromJobQueue)  Time elapsed: 0.137 s  <<< FAILURE!
2020-09-25T01:00:23.5927674Z org.apache.helix.HelixException: Failed to delete job: testForceDeleteJobFromJobQueue_job2 from queue: testForceDeleteJobFromJobQueue
2020-09-25T01:00:23.5931032Z 	at org.apache.helix.integration.task.TestDeleteJobFromJobQueue.testForceDeleteJobFromJobQueue(TestDeleteJobFromJobQueue.java:73)
2020-09-25T01:00:23.5933143Z 
2020-09-25T01:00:23.9833898Z [ERROR] Failures: 
2020-09-25T01:00:23.9836368Z [ERROR]   TestDeleteJobFromJobQueue.testForceDeleteJobFromJobQueue:73 » Helix Failed to ...
2020-09-25T01:00:23.9838007Z [ERROR] Tests run: 1204, Failures: 1, Errors: 0, Skipped: 1

**Comment by kaisun2000** [comment]
batch add to do

**Comment by kaisun2000** [comment]
>2020-09-25T00:31:09.2998076Z START TestDeleteJobFromJobQueue testForceDeleteJobFromJobQueue at Fri Sep 25 00:31:09 UTC 2020
2020-09-25T00:31:09.4152687Z 2732340 [TestNGInvoker-testForceDeleteJobFromJobQueue()] ERROR org.apache.helix.zookeeper.zkclient.ZkClient  - zkclient 5127, Failed to delete /CLUSTER_TestDeleteJobFromJobQueue/PROPERTYSTORE/TaskRebalancer/testForceDeleteJobFromJobQueue_job2, exception {}
2020-09-25T00:31:09.4205608Z org.apache.helix.zookeeper.zkclient.exception.ZkException: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /CLUSTER_TestDeleteJobFromJobQueue/PROPERTYSTORE/TaskRebalancer/testForceDeleteJobFromJobQueue_job2
2020-09-25T00:31:09.4208794Z 	at org.apache.helix.zookeeper.zkclient.exception.ZkException.create(ZkException.java:72)
2020-09-25T00:31:09.4210848Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.retryUntilConnected(ZkClient.java:1692)
2020-09-25T00:31:09.4212856Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.delete(ZkClient.java:1750)
2020-09-25T00:31:09.4214957Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.deleteRecursively(ZkClient.java:1432)
2020-09-25T00:31:09.4216865Z 	at org.apache.helix.manager.zk.ZkBaseDataAccessor.remove(ZkBaseDataAccessor.java:708)
2020-09-25T00:31:09.4219089Z 	at org.apache.helix.manager.zk.ZkCacheBaseDataAccessor.remove(ZkCacheBaseDataAccessor.java:350)
2020-09-25T00:31:09.4233249Z 	at org.apache.helix.store.zk.AutoFallbackPropertyStore.remove(AutoFallbackPropertyStore.java:95)
2020-09-25T00:31:09.4235692Z 	at org.apache.helix.task.TaskUtil.removeWorkflowJobContext(TaskUtil.java:948)
2020-09-25T00:31:09.4236962Z 	at org.apache.helix.task.TaskUtil.removeJobContext(TaskUtil.java:254)
2020-09-25T00:31:09.4237974Z 	at org.apache.helix.task.TaskUtil.removeJob(TaskUtil.java:867)
2020-09-25T00:31:09.4239081Z 	at org.apache.helix.task.TaskDriver.deleteNamespacedJob(TaskDriver.java:278)
2020-09-25T00:31:09.4240240Z 	at org.apache.helix.task.TaskDriver.deleteJob(TaskDriver.java:259)
2020-09-25T00:31:09.4242679Z 	at org.apache.helix.integration.task.TestDeleteJobFromJobQueue.testForceDeleteJobFromJobQueue(TestDeleteJobFromJobQueue.java:73)
2020-09-25T00:31:09.4245484Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-09-25T00:31:09.4247045Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-09-25T00:31:09.4248523Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-09-25T00:31:09.4249652Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-09-25T00:31:09.4250832Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76)
2020-09-25T00:31:09.4252392Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
2020-09-25T00:31:09.4298054Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
2020-09-25T00:31:09.4300104Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-09-25T00:31:09.4301199Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-25T00:31:09.4303099Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-09-25T00:31:09.4304666Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-09-25T00:31:09.4305442Z 	at java.lang.Thread.run(Thread.java:748)
2020-09-25T00:31:09.4307130Z Caused by: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /CLUSTER_TestDeleteJobFromJobQueue/PROPERTYSTORE/TaskRebalancer/testForceDeleteJobFromJobQueue_job2
2020-09-25T00:31:09.4309284Z 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:128)
2020-09-25T00:31:09.4310501Z 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
2020-09-25T00:31:09.4311974Z 	at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:882)
2020-09-25T00:31:09.4313114Z 	at org.apache.helix.zookeeper.zkclient.ZkConnection.delete(ZkConnection.java:127)
2020-09-25T00:31:09.4314578Z 	at org.apache.helix.zookeeper.zkclient.ZkClient$10.call(ZkClient.java:1754)
2020-09-25T00:31:09.4316235Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.retryUntilConnected(ZkClient.java:1678)
2020-09-25T00:31:09.4317275Z 	... 23 more
2020-09-25T00:31:09.4319614Z 2732341 [TestNGInvoker-testForceDeleteJobFromJobQueue()] ERROR org.apache.helix.manager.zk.ZkBaseDataAccessor  - Failed to delete /CLUSTER_TestDeleteJobFromJobQueue/PROPERTYSTORE/TaskRebalancer/testForceDeleteJobFromJobQueue_job2 recursively with opts 1.
2020-09-25T00:31:09.4374767Z org.apache.helix.zookeeper.exception.ZkClientException: Failed to delete /CLUSTER_TestDeleteJobFromJobQueue/PROPERTYSTORE/TaskRebalancer/testForceDeleteJobFromJobQueue_job2
2020-09-25T00:31:09.4376819Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.deleteRecursively(ZkClient.java:1435)
2020-09-25T00:31:09.4378547Z 	at org.apache.helix.manager.zk.ZkBaseDataAccessor.remove(ZkBaseDataAccessor.java:708)
2020-09-25T00:31:09.4380179Z 	at org.apache.helix.manager.zk.ZkCacheBaseDataAccessor.remove(ZkCacheBaseDataAccessor.java:350)
2020-09-25T00:31:09.4382572Z 	at org.apache.helix.store.zk.AutoFallbackPropertyStore.remove(AutoFallbackPropertyStore.java:95)
2020-09-25T00:31:09.4384848Z 	at org.apache.helix.task.TaskUtil.removeWorkflowJobContext(TaskUtil.java:948)
2020-09-25T00:31:09.4386709Z 	at org.apache.helix.task.TaskUtil.removeJobContext(TaskUtil.java:254)
2020-09-25T00:31:09.4389355Z 	at org.apache.helix.task.TaskUtil.removeJob(TaskUtil.java:867)
2020-09-25T00:31:09.4391179Z 	at org.apache.helix.task.TaskDriver.deleteNamespacedJob(TaskDriver.java:278)
2020-09-25T00:31:09.4392335Z 	at org.apache.helix.task.TaskDriver.deleteJob(TaskDriver.java:259)
2020-09-25T00:31:09.4394617Z 	at org.apache.helix.integration.task.TestDeleteJobFromJobQueue.testForceDeleteJobFromJobQueue(TestDeleteJobFromJobQueue.java:73)
2020-09-25T00:31:09.4396906Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-09-25T00:31:09.4398079Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-09-25T00:31:09.4399515Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-09-25T00:31:09.4400613Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-09-25T00:31:09.4401774Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76)
2020-09-25T00:31:09.4403290Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
2020-09-25T00:31:09.4404573Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
2020-09-25T00:31:09.4405618Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-09-25T00:31:09.4406432Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-25T00:31:09.4407876Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-09-25T00:31:09.4410083Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-09-25T00:31:09.4410877Z 	at java.lang.Thread.run(Thread.java:748)
2020-09-25T00:31:09.4413044Z Caused by: org.apache.helix.zookeeper.zkclient.exception.ZkException: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /CLUSTER_TestDeleteJobFromJobQueue/PROPERTYSTORE/TaskRebalancer/testForceDeleteJobFromJobQueue_job2
2020-09-25T00:31:09.4417260Z 	at org.apache.helix.zookeeper.zkclient.exception.ZkException.create(ZkException.java:72)
2020-09-25T00:31:09.4419620Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.retryUntilConnected(ZkClient.java:1692)
2020-09-25T00:31:09.4468334Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.delete(ZkClient.java:1750)
2020-09-25T00:31:09.4470040Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.deleteRecursively(ZkClient.java:1432)
2020-09-25T00:31:09.4470977Z 	... 21 more
2020-09-25T00:31:09.4472177Z Caused by: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /CLUSTER_TestDeleteJobFromJobQueue/PROPERTYSTORE/TaskRebalancer/testForceDeleteJobFromJobQueue_job2
2020-09-25T00:31:09.4473823Z 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:128)
2020-09-25T00:31:09.4474942Z 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
2020-09-25T00:31:09.4475915Z 	at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:882)
2020-09-25T00:31:09.4477035Z 	at org.apache.helix.zookeeper.zkclient.ZkConnection.delete(ZkConnection.java:127)
2020-09-25T00:31:09.4478269Z 	at org.apache.helix.zookeeper.zkclient.ZkClient$10.call(ZkClient.java:1754)
2020-09-25T00:31:09.4479664Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.retryUntilConnected(ZkClient.java:1678)
2020-09-25T00:31:09.4480640Z 	... 23 more
2020-09-25T00:31:09.4481233Z END TestDeleteJobFromJobQueue testForceDeleteJobFromJobQueue at Fri Sep 25 00:31:09 UTC 2020, took: 129ms.
2020-09-25T00:31:09.4482332Z AfterClass: TestDeleteJobFromJobQueue of TaskSynchronizedTestBase called.
2020-09-25T00:31:09.4484380Z 2732369 [HelixController-pipeline-task-CLUSTER_TestDeleteJobFromJobQueue-(d5272040_TASK)] ERROR org.apache.helix.task.JobDispatcher  - Job configuration is NULL for testForceDeleteJobFromJobQueue_job2
2020-09-25T00:31:09.4629535Z 2732387 [TaskJobPurgeWorker-CLUSTER_TestDeleteJobFromJobQueue] ERROR org.apache.helix.controller.pipeline.AbstractAsyncBaseStage  - Failed to process TASK::TaskGarbageCollectionStage asynchronously
2020-09-25T00:31:09.4632274Z org.apache.helix.zookeeper.zkclient.exception.ZkInterruptedException: java.lang.InterruptedException
2020-09-25T00:31:09.4634638Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.acquireEventLock(ZkClient.java:1634)
2020-09-25T00:31:09.4636604Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.waitForKeeperState(ZkClient.java:1611)
2020-09-25T00:31:09.4638501Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.waitUntilConnected(ZkClient.java:1602)
2020-09-25T00:31:09.4640151Z 	at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:396)
2020-09-25T00:31:09.4641838Z 	at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
2020-09-25T00:31:09.4643444Z 	at org.apache.helix.task.TaskUtil.workflowGarbageCollection(TaskUtil.java:1118)
2020-09-25T00:31:09.4645354Z 	at org.apache.helix.controller.stages.TaskGarbageCollectionStage.execute(TaskGarbageCollectionStage.java:126)
2020-09-25T00:31:09.4647450Z 	at org.apache.helix.controller.pipeline.AbstractAsyncBaseStage$1.run(AbstractAsyncBaseStage.java:47)
2020-09-25T00:31:09.4649138Z 	at org.apache.helix.controller.GenericHelixController$3.handleEvent(GenericHelixController.java:654)
2020-09-25T00:31:09.4650695Z 	at org.apache.helix.controller.GenericHelixController$3.handleEvent(GenericHelixController.java:650)
2020-09-25T00:31:09.4652123Z 	at org.apache.helix.common.DedupEventProcessor.run(DedupEventProcessor.java:61)
2020-09-25T00:31:09.4653060Z Caused by: java.lang.InterruptedException
2020-09-25T00:31:09.4654651Z 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1223)
2020-09-25T00:31:09.4656752Z 	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:340)
2020-09-25T00:31:09.4658364Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.acquireEventLock(ZkClient.java:1632)
2020-09-25T00:31:09.4659272Z 	... 10 more
2020-09-25T00:31:09.5314861Z AfterClass:TestDeleteJobFromJobQueue afterclass of ZkTestBase called!
2020-09-25T00:31:09.5316006Z ************ SYSTEM Physical Memory:7263748096

**Comment by kaisun2000** [comment]
LOG 1502

>2020-09-25T08:35:06.8783404Z [ERROR] Tests run: 1205, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 4,608.126 s <<< FAILURE! - in TestSuite
2020-09-25T08:35:06.8807743Z [ERROR] testForceDeleteJobFromJobQueue(org.apache.helix.integration.task.TestDeleteJobFromJobQueue)  Time elapsed: 0.17 s  <<< FAILURE!
2020-09-25T08:35:06.8810808Z org.apache.helix.HelixException: Failed to delete job: testForceDeleteJobFromJobQueue_job2 from queue: testForceDeleteJobFromJobQueue
2020-09-25T08:35:06.8815043Z 	at org.apache.helix.integration.task.TestDeleteJobFromJobQueue.testForceDeleteJobFromJobQueue(TestDeleteJobFromJobQueue.java:73)
2020-09-25T08:35:06.8818002Z 
2020-09-25T08:35:07.2724839Z [ERROR] Failures: 
2020-09-25T08:35:07.2731253Z [ERROR]   TestDeleteJobFromJobQueue.testForceDeleteJobFromJobQueue:73 » Helix Failed

**Comment by kaisun2000** [comment]
LOG 1505
> 2020-09-25T08:34:08.8691684Z [ERROR] testForceDeleteJobFromJobQueue(org.apache.helix.integration.task.TestDeleteJobFromJobQueue)  Time elapsed: 0.146 s  <<< FAILURE!
2020-09-25T08:34:08.8693946Z org.apache.helix.HelixException: Failed to delete job: testForceDeleteJobFromJobQueue_job2 from queue: testForceDeleteJobFromJobQueue
2020-09-25T08:34:08.8696797Z 	at org.apache.helix.integration.task.TestDeleteJobFromJobQueue.testForceDeleteJobFromJobQueue(TestDeleteJobFromJobQueue.java:73)
2020-09-25T08:34:08.8698837Z

**Comment by kaisun2000** [comment]
``` 
 protected static boolean removeJob(HelixDataAccessor accessor,
      HelixPropertyStore<ZNRecord> propertyStore, String job) {
    if (!removeJobConfig(accessor, job)) {
      LOG.warn(String.format("Error occurred while trying to remove job config for %s.", job));
      return false;
    }
    if (!cleanupJobIdealStateExtView(accessor, job)) {
      LOG.warn(String.format(
          "Error occurred while trying to remove job idealstate/externalview for %s.", job));
      return false;
    }
    if (!removeJobContext(propertyStore, job)) {
      LOG.warn(String.format("Error occurred while trying to remove job context for %s.", job));
      return false;
    }
    return true;
```

controller run may interfere with it. Retry force delete.
