### ISSUE TITLE
Fix flaky test TestHelixZkClient.testSharingZkClient

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1419]
LOG: 1833

>2020-09-27T21:59:01.8562468Z [ERROR] Tests run: 1207, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 4,893.999 s <<< FAILURE! - in TestSuite
2020-09-27T21:59:01.8564524Z [ERROR] testSharingZkClient(org.apache.helix.manager.zk.client.TestHelixZkClient)  Time elapsed: 0.069 s  <<< FAILURE!
2020-09-27T21:59:01.8566211Z java.lang.AssertionError: expected:<0> but was:<1>
2020-09-27T21:59:01.8568361Z 	at org.apache.helix.manager.zk.client.TestHelixZkClient.testSharingZkClient(TestHelixZkClient.java:136)
2020-09-27T21:59:01.8570253Z 
2020-09-27T21:59:02.2922515Z [ERROR] Failures: 
2020-09-27T21:59:02.2927879Z [ERROR]   TestHelixZkClient.testSharingZkClient:136 expected:<0> but was:<1>
2020-09-27T21:59:02.2933268Z [ERROR] Tests run: 1207, Failures: 1, Errors: 0, Skipped: 1
2020-09-27T21:59:02.3024076Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project helix-core: There are test failures.

**Comment by kaisun2000** [comment]
```
    // Modify using client A and client B will get notification.
    sharedZkClientA.createPersistent(TEST_PATH, true);
    Assert.assertTrue(TestHelper.verify(() -> notificationCountB[0] == 1, 1000));
    Assert.assertEquals(notificationCountB[1], 0);
```

**Comment by kaisun2000** [comment]
use TestHelper.WAIT_DURATION

**Comment by kaisun2000** [comment]
LOG 2150

>9T12:09:56.1187531Z [ERROR] Tests run: 1208, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 5,269.362 s <<< FAILURE! - in TestSuite
2020-09-29T12:09:56.1194648Z [ERROR] testSharingZkClient(org.apache.helix.manager.zk.client.TestHelixZkClient)  Time elapsed: 0.076 s  <<< FAILURE!
2020-09-29T12:09:56.1199728Z java.lang.AssertionError: expected:<0> but was:<1>
2020-09-29T12:09:56.1207896Z 	at org.apache.helix.manager.zk.client.TestHelixZkClient.testSharingZkClient(TestHelixZkClient.java:136)
2020-09-29T12:09:56.1210414Z 
2020-09-29T12:09:56.3960840Z [ERROR] Failures: 
2020-09-29T12:09:56.3962373Z [ERROR]   TestHelixZkClient.testSharingZkClient:136 expected:<0> but was:<1>

**Comment by kaisun2000** [comment]
```  
  // Modify using client A and client B will get notification.
    sharedZkClientA.createPersistent(TEST_PATH, true);
    Assert.assertTrue(TestHelper.verify(() -> notificationCountB[0] == 1, TestHelper.WAIT_DURATION));
    Assert.assertEquals(notificationCountB[1], 0);
```

**Comment by kaisun2000** [comment]
Note, both TestSharingZkClient() and previous TestZkConnectionManager() share the same test path. TestZkConnectionManager has a `deleteCluster("testZkConnectionManager");` as last operation without waiting till it is clears. This may affect the correctness of test

**Comment by kaisun2000** [comment]
LOG 2510

>START TestHelixZkClient testZkConnectionManager at Tue Oct 06 02:02:06 UTC 2020
2020-10-06T02:02:06.7570703Z END TestHelixZkClient testZkConnectionManager at Tue Oct 06 02:02:06 UTC 2020, took: 226ms.
2020-10-06T02:02:06.7571961Z START TestHelixZkClient testSharingZkClient at Tue Oct 06 02:02:06 UTC 2020
2020-10-06T02:02:06.7651298Z sharedZkClient A increased n1 with path: /testSharingZkClient/IDEALSTATES/test_helix_zkclienttestSharingZkClient
2020-10-06T02:02:06.7657051Z sharedZkClient B increased n0 with path: /testSharingZkClient/IDEALSTATES/test_helix_zkclienttestSharingZkClient
2020-10-06T02:02:06.7676143Z Created test path:/testSharingZkClient/IDEALSTATES/test_helix_zkclienttestSharingZkClient
2020-10-06T02:02:06.7683131Z sharedZkClient B increased n0 with path: /testSharingZkClient/IDEALSTATES/test_helix_zkclienttestSharingZkClient
2020-10-06T02:02:06.7684654Z sharedZkClient A increased n0 with path: /testSharingZkClient/IDEALSTATES/test_helix_zkclienttestSharingZkClient
2020-10-06T02:02:06.8269303Z END TestHelixZkClient testSharingZkClient at Tue Oct 06 02:02:06 UTC 2020, took: 70ms.
2020-10-06T02:02:06.8271632Z AfterClass:TestHelixZkClient afterclass of ZkTestBase called!

>123963Z [ERROR] Failures: 
2020-10-06T03:23:24.3129550Z [ERROR]   TestHelixZkClient.testSharingZkClient:141 expected:<0> but was:<1>

code:

```
    final int[] notificationCountA = {0, 0};
    sharedZkClientA.subscribeDataChanges(TEST_PATH, new IZkDataListener() {
      @Override
      public void handleDataChange(String s, Object o) {
        notificationCountA[0]++;
        System.out.println("sharedZkClient A increased n0 with path: " + s);
      }

      @Override
      public void handleDataDeleted(String s) {
        notificationCountA[1]++;
        System.out.println("sharedZkClient A increased n1 with path: " + s);
      }
    });
    final int[] notificationCountB = {0, 0};
    sharedZkClientB.subscribeDataChanges(TEST_PATH, new IZkDataListener() {
      @Override
      public void handleDataChange(String s, Object o) {
        notificationCountB[0]++;
        System.out.println("sharedZkClient B increased n0 with path: " + s);
      }

      @Override
      public void handleDataDeleted(String s) {
        notificationCountB[1]++;
        System.out.println("sharedZkClient B increased n1 with path: " + s);
      }
    });

    // Modify using client A and client B will get notification.
    sharedZkClientA.createPersistent(TEST_PATH, true);
    System.out.println("Created test path:" + TEST_PATH);
    Assert.assertTrue(TestHelper.verify(() -> notificationCountB[0] == 1, TestHelper.WAIT_DURATION));
    Assert.assertEquals(notificationCountB[1], 0);

```

**Comment by kaisun2000** [comment]
It seems that handleDelete was called for both A and B. Not sure where it is from. This is very rare happening.

add a little bit more log.
