### ISSUE TITLE
TestP2PSingleTopState.testRollingUpgrade

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1423]
LOG 2184

>2020-09-29T12:30:29.6139014Z [ERROR] testRollingUpgrade(org.apache.helix.integration.messaging.TestP2PSingleTopState)  Time elapsed: 300.446 s  <<< FAILURE!
2020-09-29T12:30:29.6140525Z java.lang.AssertionError: expected:< true> but was:< false>
2020-09-29T12:30:29.6143086Z 	at org.apache.helix.integration.messaging.TestP2PSingleTopState.testRollingUpgrade(TestP2PSingleTopState.java:143)
2020-09-29T12:30:29.6144998Z 
2020-09-29T12:30:30.0409436Z [ERROR] Failures: 
2020-09-29T12:30:30.0411091Z [ERROR]   TestP2PSingleTopState.testRollingUpgrade:143 expected:< true> but was:< false>

**Comment by kaisun2000** [comment]
public void testRollingUpgrade() throws InterruptedException {
    // rolling upgrade the cluster
    for (String ins : _instances) {
      System.out.println("Disable " + ins);
      _gSetupTool.getClusterManagementTool().enableInstance(CLUSTER_NAME, ins, false);
      //Thread.sleep(1000L);
      Assert.assertTrue(_clusterVerifier.verifyByPolling());     ---> failed.
      System.out.println("Enable " + ins);
      _gSetupTool.getClusterManagementTool().enableInstance(CLUSTER_NAME, ins, true);
      //Thread.sleep(1000L);
      Assert.assertTrue(_clusterVerifier.verifyByPolling());
    }

    Assert.assertTrue(_clusterVerifier.verifyByPolling());
    Assert.assertFalse(TestTransition.duplicatedPartitionsSnapshot.keys().hasMoreElements());
  }

**Comment by kaisun2000** [comment]
More LOG

>020-09-29T12:11:32.4935608Z START TestP2PSingleTopState testRollingUpgrade at Tue Sep 29 12:11:31 UTC 2020
2020-09-29T12:11:32.4936077Z Disable localhost_12918
2020-09-29T12:11:32.4938891Z 4325762 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(5a464b46)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_41 matches the hosted message's target state, set relay message 3ddf08f2-f7ee-40ef-bc55-80dedd561617 to be expired.
2020-09-29T12:11:32.4942608Z 4325762 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(5a464b46)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_0_48 matches the hosted message's target state, set relay message d11f1836-104a-447e-9361-d12065a7d204 to be expired.
2020-09-29T12:11:32.4946285Z 4325762 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(5a464b46)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_20 matches the hosted message's target state, set relay message 3659846a-1fd7-42db-9b13-a5ba23971f49 to be expired.
2020-09-29T12:11:32.4949658Z 4325762 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(5a464b46)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_21 matches the hosted message's target state, set relay message bd189324-89c4-4714-a2d0-2f94985626c0 to be expired.
2020-09-29T12:11:32.4954899Z 4325762 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(5a464b46)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_0_10 matches the hosted message's target state, set relay message 4f1aa02b-3874-435c-9908-e0523e9f6ffe to be expired.
2020-09-29T12:11:32.4958432Z 4325762 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(5a464b46)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_40 matches the hosted message's target state, set relay message 0cca10e0-ac8c-412a-acc6-203e87dd7e99 to be expired.
2020-09-29T12:11:32.4962052Z 4325762 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(5a464b46)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_3 matches the hosted message's target state, set relay message b152982b-d14e-4f13-a41d-ef34b00875a5 to be expired.
2020-09-29T12:11:32.4966726Z 4325762 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(5a464b46)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_17 matches the hosted message's target state, set relay message 5c6eab3b-5823-445d-b1e2-3dd841590126 to be expired.
2020-09-29T12:11:32.4970679Z 4325762 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(5a464b46)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_6 matches the hosted message's target state, set relay message 1e46741b-415f-44f9-a116-5fc0d3d74dc5 to be expired.
2020-09-29T12:11:32.4974485Z 4325762 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(5a464b46)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_8 matches the hosted message's target state, set relay message bf480679-21fa-4f81-bc61-9738e4f06f25 to be expired.
2020-09-29T12:11:32.4977670Z 4325762 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(5a464b46)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_25 matches the hosted message's target state, set relay message ea59472a-e348-4b45-a1e4-406b8d64e871 to be expired.
2020-09-29T12:11:32.4982674Z 4325762 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(5a464b46)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_24 matches the hosted message's target state, set relay message fb4a04a9-5a3b-4e38-a309-01ea1219944f to be expired.
2020-09-29T12:11:32.4986186Z 4325797 [HelixController-pipeline-task-CLUSTER_TestP2PSingleTopState-(cdc410c6_TASK)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_17 matches the hosted message's target state, set relay message 5c6eab3b-5823-445d-b1e2-3dd841590126 to be expired.
2020-09-29T12:11:32.4991009Z 4325797 [HelixController-pipeline-task-CLUSTER_TestP2PSingleTopState-(cdc410c6_TASK)] INFO  org.apache.helix.controller.dataproviders.WorkflowControllerDataProvider  - Event cdc410c6_TASK : END: WorkflowControllerDataProvider.refresh() for cluster CLUSTER_TestP2PSingleTopState, started at 1601381491172 took 25 for TASK pipeline
2020-09-29T12:11:32.4998603Z 4325805 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(cdc410c6_DEFAULT)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_41 matches the hosted message's target state, set relay message 3ddf08f2-f7ee-40ef-bc55-80dedd561617 to be expired.
2020-09-29T12:11:32.5007202Z 4325805 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(cdc410c6_DEFAULT)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_0_48 matches the hosted message's target state, set relay message d11f1836-104a-447e-9361-d12065a7d204 to be expired.
2020-09-29T12:11:32.5016543Z 4325805 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(cdc410c6_DEFAULT)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_20 matches the hosted message's target state, set relay message 3659846a-1fd7-42db-9b13-a5ba23971f49 to be expired.
2020-09-29T12:11:32.5024397Z 4325805 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(cdc410c6_DEFAULT)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_21 matches the hosted message's target state, set relay message bd189324-89c4-4714-a2d0-2f94985626c0 to be expired.
2020-09-29T12:11:32.5030710Z 4325805 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(cdc410c6_DEFAULT)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_0_10 matches the hosted message's target state, set relay message 4f1aa02b-3874-435c-9908-e0523e9f6ffe to be expired.
2020-09-29T12:11:32.5035011Z 4325805 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(cdc410c6_DEFAULT)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_40 matches the hosted message's target state, set relay message 0cca10e0-ac8c-412a-acc6-203e87dd7e99 to be expired.
2020-09-29T12:11:32.5044433Z 4325805 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(cdc410c6_DEFAULT)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_3 matches the hosted message's target state, set relay message b152982b-d14e-4f13-a41d-ef34b00875a5 to be expired.
2020-09-29T12:11:32.5056295Z 4325805 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(cdc410c6_DEFAULT)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_17 matches the hosted message's target state, set relay message 5c6eab3b-5823-445d-b1e2-3dd841590126 to be expired.
2020-09-29T12:11:32.5060309Z 4325805 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(cdc410c6_DEFAULT)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_6 matches the hosted message's target state, set relay message 1e46741b-415f-44f9-a116-5fc0d3d74dc5 to be expired.
2020-09-29T12:11:32.5065443Z 4325805 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(cdc410c6_DEFAULT)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_8 matches the hosted message's target state, set relay message bf480679-21fa-4f81-bc61-9738e4f06f25 to be expired.
2020-09-29T12:11:32.5073169Z 4325805 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(cdc410c6_DEFAULT)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_25 matches the hosted message's target state, set relay message ea59472a-e348-4b45-a1e4-406b8d64e871 to be expired.
2020-09-29T12:11:32.5078638Z 4325805 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(cdc410c6_DEFAULT)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_24 matches the hosted message's target state, set relay message fb4a04a9-5a3b-4e38-a309-01ea1219944f to be expired.
2020-09-29T12:11:32.5083435Z 4325898 [HelixController-pipeline-task-CLUSTER_TestP2PSingleTopState-(bd2f8626)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_17 matches the hosted message's target state, set relay message 5c6eab3b-5823-445d-b1e2-3dd841590126 to be expired.
2020-09-29T12:11:32.5091112Z 4325901 [HelixController-pipeline-task-CLUSTER_TestP2PSingleTopState-(bd2f8626)] INFO  org.apache.helix.controller.dataproviders.WorkflowControllerDataProvider  - Event bd2f8626 : END: WorkflowControllerDataProvider.refresh() for cluster CLUSTER_TestP2PSingleTopState, started at 1601381491238 took 63 for TASK pipeline
2020-09-29T12:11:32.5097705Z 4325911 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(bd2f8626)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_22 matches the hosted message's target state, set relay message f58960aa-8114-46f5-8650-22377e250036 to be expired.

...

org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_3 matches the hosted message's target state, set relay message b152982b-d14e-4f13-a41d-ef34b00875a5 to be expired.
2020-09-29T12:11:34.2065834Z 4328805 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(89f1ea44)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_6 matches the hosted message's target state, set relay message 1e46741b-415f-44f9-a116-5fc0d3d74dc5 to be expired.
2020-09-29T12:11:34.2069486Z 4328805 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(89f1ea44)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_8 matches the hosted message's target state, set relay message bf480679-21fa-4f81-bc61-9738e4f06f25 to be expired.
2020-09-29T12:11:34.2073777Z 4328805 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(89f1ea44)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_25 matches the hosted message's target state, set relay message ea59472a-e348-4b45-a1e4-406b8d64e871 to be expired.
2020-09-29T12:11:34.2089299Z 4328807 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(89f1ea44)] ERROR org.apache.helix.common.caches.InstanceMessagesCache  - Target state for partition TestDB_1_24 matches the hosted message's target state, set relay message fb4a04a9-5a3b-4e38-a309-01ea1219944f to be expired.
2020-09-29T12:11:34.2092393Z 4328807 [HelixController-pipeline-default-CLUSTER_TestP2PSingleTopState-(89f1ea44)] ERROR org.apache.helix.util.RebalanceUtil  - Failed to issue a pipeline run. Delay is invalid.
2020-09-29T12:11:34.2114998Z 4328809 [HelixController-pipeline-task-CLUSTER_TestP2PSingleTopState-(89f1ea44)] INFO  org.apache.helix.controller.dataproviders.WorkflowControllerDataProvider  - Event 89f1ea44 : END: WorkflowControllerDataProvider.refresh() for cluster CLUSTER_TestP2PSingleTopState, started at 1601381494179 took 30 for TASK pipeline
2020-09-29T12:15:11.0523246Z 4545623 [TaskStateModelFactory-task_thread-11] ERROR org.apache.helix.task.TaskRunner  - Problem running the task, report task as FAILED.
2020-09-29T12:15:11.0524965Z org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
2020-09-29T12:15:11.0526421Z 	at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:388)
2020-09-29T12:15:11.0528764Z 	at org.apache.helix.manager.zk.ZKHelixManager.getHelixPropertyStore(ZKHelixManager.java:1015)
2020-09-29T12:15:11.0531395Z 	at org.apache.helix.task.UserContentStore.getUserContent(UserContentStore.java:102)
2020-09-29T12:15:11.0533295Z 	at org.apache.helix.integration.task.MockTask.run(MockTask.java:149)
2020-09-29T12:15:11.0534574Z 	at org.apache.helix.task.TaskRunner.run(TaskRunner.java:71)
2020-09-29T12:15:11.0535524Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-09-29T12:15:11.0536469Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-29T12:15:11.0538893Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
2020-09-29T12:15:11.0541857Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
2020-09-29T12:15:11.0545061Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-09-29T12:15:11.0546781Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-09-29T12:15:11.0547930Z 	at java.lang.Thread.run(Thread.java:748)
2020-09-29T12:15:11.0549271Z 4545648 [TaskStateModelFactory-task_thread-11] ERROR org.apache.helix.task.TaskRunner  - Problem running the task, report task as FAILED.
2020-09-29T12:15:11.0550562Z org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
2020-09-29T12:15:11.0552054Z 	at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:388)
2020-09-29T12:15:11.0554042Z 	at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
2020-09-29T12:15:11.0561967Z 	at org.apache.helix.task.TaskRunner.requestStateTransition(TaskRunner.java:184)
2020-09-29T12:15:11.0563306Z 	at org.apache.helix.task.TaskRunner.run(TaskRunner.java:93)
2020-09-29T12:15:11.0564288Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-09-29T12:15:11.0566114Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-29T12:15:11.0567703Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
2020-09-29T12:15:11.0570853Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
2020-09-29T12:15:11.0572683Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-09-29T12:15:11.0574104Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-09-29T12:15:11.0574988Z 	at java.lang.Thread.run(Thread.java:748)
2020-09-29T12:15:11.0578068Z 4545649 [HelixTaskExecutor-message_handle_thread_29751] ERROR org.apache.helix.messaging.handling.HelixStateTransitionHandler  - Exception while executing a state transition task testStopWorkflowInStoppingState_Job1_0
2020-09-29T12:15:11.0581013Z java.lang.reflect.InvocationTargetException
2020-09-29T12:15:11.0582295Z 	at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
2020-09-29T12:15:11.0584600Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-09-29T12:15:11.0585872Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-09-29T12:15:11.0588439Z 	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.invoke(HelixStateTransitionHandler.java:404)
2020-09-29T12:15:11.0592762Z 	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.handleMessage(HelixStateTransitionHandler.java:331)
2020-09-29T12:15:11.0596246Z 	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:97)
2020-09-29T12:15:11.0598629Z 	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49)
2020-09-29T12:15:11.0599934Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-29T12:15:11.0601300Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-09-29T12:15:11.0602680Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-09-29T12:15:11.0603535Z 	at java.lang.Thread.run(Thread.java:748)
2020-09-29T12:15:11.0604064Z Caused by: java.lang.NullPointerException
2020-09-29T12:15:11.0605391Z 	at org.apache.helix.task.TaskStateModel.onBecomeStoppedFromRunning(TaskStateModel.java:94)
2020-09-29T12:15:11.0606509Z 	... 11 more
2020-09-29T12:15:11.0607885Z 4545649 [HelixTaskExecutor-message_handle_thread_29751] ERROR org.apache.helix.util.StatusUpdateUtil  - Exception while logging status update
2020-09-29T12:15:11.0609433Z org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
2020-09-29T12:15:11.0611120Z 	at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:388)
2020-09-29T12:15:11.0613824Z 	at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
2020-09-29T12:15:11.0617789Z 	at org.apache.helix.util.StatusUpdateUtil.logMessageStatusUpdateRecord(StatusUpdateUtil.java:349)
2020-09-29T12:15:11.0620149Z 	at org.apache.helix.util.StatusUpdateUtil.logError(StatusUpdateUtil.java:401)
2020-09-29T12:15:11.0626276Z 	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.handleMessage(HelixStateTransitionHandler.java:359)
2020-09-29T12:15:11.0630594Z 	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:97)
2020-09-29T12:15:11.0632328Z 	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49)
2020-09-29T12:15:11.0633424Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-29T12:15:11.0635660Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-09-29T12:15:11.0637067Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-09-29T12:15:11.0637917Z 	at java.lang.Thread.run(Thread.java:748)
2020-09-29T12:15:11.0640139Z 4545649 [HelixTaskExecutor-message_handle_thread_29751] ERROR org.apache.helix.messaging.handling.HelixTask  - Exception while executing a message. org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect() msgId: ca0e487d-d321-4e9c-92be-d79037838903 type: STATE_TRANSITION
2020-09-29T12:15:11.0643053Z org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
2020-09-29T12:15:11.0644474Z 	at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:388)
2020-09-29T12:15:11.0646766Z 	at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
2020-09-29T12:15:11.0650768Z 	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.postHandleMessage(HelixStateTransitionHandler.java:191)
2020-09-29T12:15:11.0654671Z 	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.handleMessage(HelixStateTransitionHandler.java:371)
2020-09-29T12:15:11.0658138Z 	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:97)
2020-09-29T12:15:11.0661977Z 	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49)
2020-09-29T12:15:11.0663098Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-29T12:15:11.0665973Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-09-29T12:15:11.0672017Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-09-29T12:15:11.0673873Z 	at java.lang.Thread.run(Thread.java:748)
2020-09-29T12:15:11.0730086Z 4545649 [HelixTaskExecutor-message_handle_thread_29751] ERROR org.apache.helix.util.StatusUpdateUtil  - Exception while logging status update
2020-09-29T12:15:11.0731381Z org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
2020-09-29T12:15:11.0733122Z 	at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:388)
2020-09-29T12:15:11.0735169Z 	at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
2020-09-29T12:15:11.0737532Z 	at org.apache.helix.util.StatusUpdateUtil.logMessageStatusUpdateRecord(StatusUpdateUtil.java:349)
2020-09-29T12:15:11.0739469Z 	at org.apache.helix.util.StatusUpdateUtil.logError(StatusUpdateUtil.java:401)
2020-09-29T12:15:11.0740790Z 	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:119)
2020-09-29T12:15:11.0742100Z 	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49)
2020-09-29T12:15:11.0743182Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-29T12:15:11.0744526Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-09-29T12:15:11.0745898Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-09-29T12:15:11.0746913Z 	at java.lang.Thread.run(Thread.java:748)
2020-09-29T12:15:11.0748710Z 4545649 [HelixTaskExecutor-message_handle_thread_29751] ERROR org.apache.helix.messaging.handling.HelixTask  - Message execution failed. msgId: ca0e487d-d321-4e9c-92be-d79037838903, errorMsg: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
2020-09-29T12:15:11.0750835Z 4545649 [HelixTaskExecutor-message_handle_thread_29751] ERROR org.apache.helix.util.StatusUpdateUtil  - Exception while logging status update
2020-09-29T12:15:11.0752227Z org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
2020-09-29T12:15:11.0753540Z 	at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:388)
2020-09-29T12:15:11.0756034Z 	at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
2020-09-29T12:15:11.0758965Z 	at org.apache.helix.util.StatusUpdateUtil.logMessageStatusUpdateRecord(StatusUpdateUtil.java:349)
2020-09-29T12:15:11.0760669Z 	at org.apache.helix.util.StatusUpdateUtil.logError(StatusUpdateUtil.java:393)
2020-09-29T12:15:11.0762182Z 	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:166)
2020-09-29T12:15:11.0763493Z 	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49)
2020-09-29T12:15:11.0764767Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-29T12:15:11.0765959Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-09-29T12:15:11.0767452Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-09-29T12:15:11.0768276Z 	at java.lang.Thread.run(Thread.java:748)
2020-09-29T12:15:11.0769749Z 4545649 [HelixTaskExecutor-message_handle_thread_29751] ERROR org.apache.helix.messaging.handling.HelixTask  - Error to final clean up for message : ca0e487d-d321-4e9c-92be-d79037838903
2020-09-29T12:15:11.0773616Z 4545649 [HelixTaskExecutor-message_handle_thread_29751] ERROR org.apache.helix.messaging.handling.HelixTask  - Exception after executing a message, msgId: ca0e487d-d321-4e9c-92be-d79037838903org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
2020-09-29T12:15:11.0776248Z org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
2020-09-29T12:15:11.0778402Z 	at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:388)
2020-09-29T12:15:11.0780165Z 	at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
2020-09-29T12:15:11.0782822Z 	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:172)
2020-09-29T12:15:11.0785079Z 	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49)
2020-09-29T12:15:11.0786326Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-29T12:15:11.0787466Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-09-29T12:15:11.0788870Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-09-29T12:15:11.0789694Z 	at java.lang.Thread.run(Thread.java:748)
2020-09-29T12:15:11.0790887Z 4545650 [HelixTaskExecutor-message_handle_thread_29751] ERROR org.apache.helix.util.StatusUpdateUtil  - Exception while logging status update
2020-09-29T12:15:11.0792114Z org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
2020-09-29T12:15:11.0793707Z 	at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:388)
2020-09-29T12:15:11.0796319Z 	at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
2020-09-29T12:15:11.0798572Z 	at org.apache.helix.util.StatusUpdateUtil.logMessageStatusUpdateRecord(StatusUpdateUtil.java:349)
2020-09-29T12:15:11.0800336Z 	at org.apache.helix.util.StatusUpdateUtil.logError(StatusUpdateUtil.java:393)
2020-09-29T12:15:11.0801862Z 	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:195)
2020-09-29T12:15:11.0803218Z 	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49)
2020-09-29T12:15:11.0804330Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-29T12:15:11.0805505Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-09-29T12:15:11.0806881Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-09-29T12:15:11.0807728Z 	at java.lang.Thread.run(Thread.java:748)
2020-09-29T12:16:23.6875756Z 4618286 [Helix-RouterUpdater-event_process-TestZkCallbackHandlerLeak_testCurrentStatePathLeakingByAsycRemoval] ERROR org.apache.helix.spectator.RoutingTableProvider  - HelixManager is not connected for router update event: Event id : 9424f190-44df-489e-acd6-e682a89c5f43name:PeriodicalRebalance
2020-09-29T12:16:23.6878815Z changeContext:org.apache.helix.NotificationContext@28220708
2020-09-29T12:16:23.6880166Z helixmanager:org.apache.helix.integration.manager.ClusterSpectatorManager@6f7fb87f
2020-09-29T12:16:23.6881387Z 
2020-09-29T12:16:23.6884577Z 4618286 [Helix-RouterUpdater-event_process-TestZkCallbackHandlerLeak_testCurrentStatePathLeakingByAsycRemoval] ERROR org.apache.helix.common.DedupEventProcessor  - Helix-RouterUpdater-event_process thread failed while running Helix-RouterUpdater-event_process
2020-09-29T12:16:23.6887218Z org.apache.helix.HelixException: HelixManager is not connected for router update event.
2020-09-29T12:16:23.6888645Z 	at org.apache.helix.spectator.RoutingTableProvider$RouterUpdater.handleEvent(RoutingTableProvider.java:914)
2020-09-29T12:16:23.6890301Z 	at org.apache.helix.spectator.RoutingTableProvider$RouterUpdater.handleEvent(RoutingTableProvider.java:878)
2020-09-29T12:16:23.6891778Z 	at org.apache.helix.common.DedupEventProcessor.run(DedupEventProcessor.java:61)
2020-09-29T12:16:32.9197745Z 4627519 [TestNGInvoker-testRollingUpgrade()] ERROR org.apache.helix.tools.ClusterVerifiers.ZkHelixClusterVerifier  - verifier timeout out with timeout 300000
2020-09-29T12:16:32.9371442Z END TestP2PSingleTopState testRollingUpgrade at Tue Sep 29 12:16:32 UTC 2020, took: 301781ms.
2020-09-29T12:16:32.9373544Z AfterClass: TestP2PSingleTopState of TestP2PSingleTopState called.
2020-09-29T12:16:33.3168792Z END TestP2PSingleTopState at Tue Sep 29 12:16:33 UTC 2020
2020-09-29T12:16:33.3170162Z AfterClass:TestP2PSingleTopState afterclass of ZkTestBase called!
