### ISSUE TITLE
fix TestDropCurrentStateRunningTask.testDropCurrentStateRunningTask

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1457]
LOG 2899
>2020-10-10T05:06:58.6016712Z [ERROR] Tests run: 1211, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 5,297.662 s <<< FAILURE! - in TestSuite
2020-10-10T05:06:58.6019017Z [ERROR] testDropCurrentStateRunningTask(org.apache.helix.integration.task.TestDropCurrentStateRunningTask)  Time elapsed: 62.391 s  <<< FAILURE!
2020-10-10T05:06:58.6056240Z org.apache.helix.HelixException: Fail to stop the workflow/queue testDropCurrentStateRunningTask with in 60000 milliseconds.
2020-10-10T05:06:58.6059726Z 	at org.apache.helix.integration.task.TestDropCurrentStateRunningTask.testDropCurrentStateRunningTask(TestDropCurrentStateRunningTask.java:152)
2020-10-10T05:06:58.6063378Z 
2020-10-10T05:06:58.9922822Z [ERROR] Failures: 
2020-10-10T05:06:58.9928845Z [ERROR]   TestDropCurrentStateRunningTask.testDropCurrentStateRunningTask:152 » Helix Fa...
2020-10-10T05:06:58.9930560Z [ERROR] Tests run: 1211, Failures: 1, Errors: 0, Skipped: 1

**Comment by kaisun2000** [comment]
cc: @alirezazamani

**Comment by kaisun2000** [comment]
2020-10-10T03:48:18.5395568Z START TestDropCurrentStateRunningTask testDropCurrentStateRunningTask at Sat Oct 10 03:48:18 UTC 2020
2020-10-10T03:48:18.6956488Z 567180 [ZkClient-EventThread-10033-localhost:2183] ERROR org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks  - Interrupted waiting for success
2020-10-10T03:48:18.6958575Z java.lang.InterruptedException
2020-10-10T03:48:18.6959535Z 	at java.lang.Object.wait(Native Method)
2020-10-10T03:48:18.6960103Z 	at java.lang.Object.wait(Object.java:502)
2020-10-10T03:48:18.6961561Z 	at org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks$DefaultCallback.waitForSuccess(ZkAsyncCallbacks.java:220)
2020-10-10T03:48:18.6963683Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.issueSync(ZkClient.java:1278)
2020-10-10T03:48:18.6965204Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.access$300(ZkClient.java:84)
2020-10-10T03:48:18.6966637Z 	at org.apache.helix.zookeeper.zkclient.ZkClient$4.run(ZkClient.java:1304)
2020-10-10T03:48:18.6967971Z 	at org.apache.helix.zookeeper.zkclient.ZkEventThread.run(ZkEventThread.java:99)
2020-10-10T03:48:20.8114969Z 569294 [HelixTaskExecutor-message_handle_thread_4351] ERROR org.apache.helix.task.TaskStateModel  - Participant localhost_12918's thread for task partition testDropCurrentStateRunningTask_JOB0_0 not found while attempting to cancel the task; Manual cleanup may be required.
2020-10-10T03:48:20.8406227Z 569320 [HelixTaskExecutor-message_handle_thread_4352] ERROR org.apache.helix.task.TaskStateModel  - Participant localhost_12919's thread for task partition testDropCurrentStateRunningTask_JOB0_0 not found while attempting to cancel the task; Manual cleanup may be required.
2020-10-10T03:49:20.9323408Z END TestDropCurrentStateRunningTask testDropCurrentStateRunningTask at Sat Oct 10 03:49:20 UTC 2020, took: 62391ms.

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
