### ISSUE TITLE
NPE from ZkAsyncCallbacks when rc is 255

### ISSUE THREAD

**Issue by pkuwm** [apache/helix#1595]
### Description
Because ZK's `KeeperException` Code does not define 255 in its map, the lookup for 255 gives null, and in `ZkAsyncCalbacks`, the code `switch (Code.get(rc))` will be `switch(null)` so NPE is thrown.

```
2637 [main] ERROR org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks  - Failed to handle unknown return code 255. Skip retrying.
java.lang.NullPointerException
        at org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks$DefaultCallback.needRetry(ZkAsyncCallbacks.java:257)
        at org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks$DefaultCallback.callback(ZkAsyncCallbacks.java:179)
        at org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks$CreateCallbackHandler.processResult(ZkAsyncCallbacks.java:104)
        at org.apache.helix.zookeeper.zkclient.ZkClient.doAsyncCreate(ZkClient.java:1958)
        at org.apache.helix.zookeeper.zkclient.ZkClient.asyncCreate(ZkClient.java:1937)
        at org.apache.helix.zookeeper.impl.client.TestRawZkClient.testAsyncWriteByExpectedSession(TestRawZkClient.java:881)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
        at org.testng.TestRunner.privateRun(TestRunner.java:749)
        at org.testng.TestRunner.run(TestRunner.java:600)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
        at org.testng.SuiteRunner.run(SuiteRunner.java:223)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1039)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:964)
        at org.testng.TestNG.run(TestNG.java:900)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
        at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by pkuwm** [comment]
NPE is caught and stack trace is logged as error. So the log is seen. No need to fix
