### ISSUE TITLE
flaky test rest.server.TestClusterAccessor.testActivateSuperCluster

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1632]
https://github.com/apache/helix/runs/1822423155?check_suite_focus=true
https://github.com/apache/helix/actions/runs/532426859/workflow

LOG>
2021-02-03T12:35:50.2416648Z [ERROR] Tests run: 171, Failures: 1, Errors: 0, Skipped: 15, Time elapsed: 134.909 s <<< FAILURE! - in TestSuite
2021-02-03T12:35:50.2427696Z [ERROR] testActivateSuperCluster(org.apache.helix.rest.server.TestClusterAccessor) Time elapsed: 14.759 s <<< FAILURE!
2021-02-03T12:35:50.2433836Z java.lang.AssertionError: expected:<true> but was:<false>
2021-02-03T12:35:50.2443528Z at org.apache.helix.rest.server.TestClusterAccessor.testActivateSuperCluster(TestClusterAccessor.java:679)
2021-02-03T12:35:50.2446559Z
2021-02-03T12:35:50.6026970Z [ERROR] Failures:
2021-02-03T12:35:50.6034331Z [ERROR] TestClusterAccessor.testActivateSuperCluster:679 expected:<true> but was:<false>
2021-02-03T12:35:50.6035918Z [ERROR] Tests run: 171, Failures: 1, Errors: 0, Skipped: 15

**Comment by kaisun2000** [comment]
2021-02-07T00:54:57.0648469Z Start test :testActivateSuperCluster
2021-02-07T00:54:57.9903022Z 46659 [ZkClient-EventThread-2012-localhost:2123] ERROR org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks  - Interrupted waiting for success
2021-02-07T00:54:57.9905732Z java.lang.InterruptedException
2021-02-07T00:54:57.9906943Z 	at java.lang.Object.wait(Native Method)
2021-02-07T00:54:57.9907892Z 	at java.lang.Object.wait(Object.java:502)
2021-02-07T00:54:57.9909663Z 	at org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks$DefaultCallback.waitForSuccess(ZkAsyncCallbacks.java:220)
2021-02-07T00:54:57.9911968Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.issueSync(ZkClient.java:1299)
2021-02-07T00:54:57.9913811Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.access$300(ZkClient.java:85)
2021-02-07T00:54:57.9915368Z 	at org.apache.helix.zookeeper.zkclient.ZkClient$4.run(ZkClient.java:1325)
2021-02-07T00:54:57.9917062Z 	at org.apache.helix.zookeeper.zkclient.ZkEventThread.run(ZkEventThread.java:99)
**2021-02-07T00:55:00.1898872Z 48855 [pool-74-thread-1] ERROR org.apache.helix.controller.GenericHelixController  - Failed to schedule a future pipeline run for cluster RestSuperClusterActivationTest_SuperCluster. Helix manager is null!**
2021-02-07T00:55:12.2179828Z 60882 [main] ERROR org.apache.helix.TestHelper  - verifier time out, consider try longer timeout, stack trace[java.lang.Thread.getStackTrace(Thread.java:1559), org.apache.helix.TestHelper.verify(TestHelper.java:813), org.apache.helix.rest.server.TestClusterAccessor.testActivateSuperCluster(TestClusterAccessor.java:672), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76), org.testng.internal.Invoker.invokeMethod(Invoker.java:673), org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846), org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170), org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125), org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109), org.testng.TestRunner.runWorkers(TestRunner.java:1147), org.testng.TestRunner.privateRun(TestRunner.java:749), org.testng.TestRunner.run(TestRunner.java:600), org.testng.SuiteRunner.runTest(SuiteRunner.java:317), org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312), org.testng.SuiteRunner.privateRun(SuiteRunner.java:274), org.testng.SuiteRunner.run(SuiteRunner.java:223), org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52), org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86), org.testng.TestNG.runSuitesSequentially(TestNG.java:1039), org.testng.TestNG.runSuitesLocally(TestNG.java:964), org.testng.TestNG.run(TestNG.java:900), org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283), org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75), org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120), org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384), org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345), org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126), org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)]

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
