### ISSUE TITLE
Flaky test Helix Rest Server starting up 

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1633]
https://github.com/apache/helix/actions/runs/529362389/workflow
https://github.com/apache/helix/actions/runs/502600385/workflow

LOG>
2021-01-22T01:38:45.9813767Z env:
2021-01-22T01:38:45.9814082Z JAVA_HOME_8.0.282_x64: /opt/hostedtoolcache/jdk/8.0.282/x64
2021-01-22T01:38:45.9814444Z JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.282/x64
2021-01-22T01:38:45.9814817Z JAVA_HOME_8_0_282_X64: /opt/hostedtoolcache/jdk/8.0.282/x64
2021-01-22T01:38:45.9815293Z ##[endgroup]
2021-01-22T01:38:52.8068852Z Start zookeeper at localhost:2123 in thread main
2021-01-22T01:38:53.0855186Z Start zookeeper at localhost:2124 in thread main
2021-01-22T01:38:54.6266217Z 0 [ZkClient-EventThread-107-localhost:2123] ERROR org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks - Interrupted waiting for success
2021-01-22T01:38:54.6267739Z java.lang.InterruptedException
2021-01-22T01:38:54.6268231Z at java.lang.Object.wait(Native Method)
2021-01-22T01:38:54.6268714Z at java.lang.Object.wait(Object.java:502)
2021-01-22T01:38:54.6307764Z at org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks$DefaultCallback.waitForSuccess(ZkAsyncCallbacks.java:220)
2021-01-22T01:38:54.6347542Z at org.apache.helix.zookeeper.zkclient.ZkClient.issueSync(ZkClient.java:1299)
2021-01-22T01:38:54.6348444Z at org.apache.helix.zookeeper.zkclient.ZkClient.access$300(ZkClient.java:85)
2021-01-22T01:38:54.6356640Z at org.apache.helix.zookeeper.zkclient.ZkClient$4.run(ZkClient.java:1325)
2021-01-22T01:38:54.6365363Z at org.apache.helix.zookeeper.zkclient.ZkEventThread.run(ZkEventThread.java:99)
2021-01-22T01:38:59.5116126Z 4891 [ZkClient-EventThread-406-localhost:2123] ERROR org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks - Interrupted waiting for success
2021-01-22T01:38:59.5117426Z java.lang.InterruptedException
2021-01-22T01:38:59.5119443Z at java.lang.Object.wait(Native Method)
2021-01-22T01:38:59.5119951Z at java.lang.Object.wait(Object.java:502)

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
