### ISSUE TITLE
Jackson 1.x serializer does not work with ZNRecord

### ISSUE THREAD

**Issue by pkuwm** [apache/helix#1655]
### Description
"org.codehaus.jackson:jackson-mapper-asl:1.9.13" because 1.9.13 can not deserialize the bytes when used by helix client.

```
org.codehaus.jackson.map.JsonMappingException: Type variable 'T' can not be resolved (with context of class org.apache.helix.zookeeper.datamodel.ZNRecord)
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCache2(StdDeserializerProvider.java:315) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
        at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCacheValueDeserializer(StdDeserializerProvider.java:290) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
        at org.codehaus.jackson.map.deser.StdDeserializerProvider.findValueDeserializer(StdDeserializerProvider.java:159) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
        at org.codehaus.jackson.map.deser.StdDeserializerProvider.findTypedValueDeserializer(StdDeserializerProvider.java:180) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
        at org.codehaus.jackson.map.ObjectMapper._findRootDeserializer(ObjectMapper.java:2829) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
        at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2728) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1909) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
        at com.abc.PropertyCompressedJsonSerializer.deserialize(PropertyCompressedJsonSerializer.java:81) []
        at org.apache.helix.zookeeper.zkclient.serialize.BasicZkSerializer.deserialize(BasicZkSerializer.java:39) [helix-core-1.0.1.2402.jar:1.0.1.2402]
        at org.apache.helix.zookeeper.zkclient.ZkClient.deserialize(ZkClient.java:1791) [helix-core-1.0.1.2402.jar:1.0.1.2402]
        at org.apache.helix.zookeeper.zkclient.ZkClient.readData(ZkClient.java:1830) [helix-core-1.0.1.2402.jar:1.0.1.2402]
        at org.apache.helix.zookeeper.zkclient.ZkClient.readData(ZkClient.java:1814) [helix-core-1.0.1.2402.jar:1.0.1.2402]
        at org.apache.helix.manager.zk.ZkBaseDataAccessor.get(ZkBaseDataAccessor.java:472) [helix-core-1.0.1.2402.jar:1.0.1.2402]
        at org.apache.helix.manager.zk.ZkCacheBaseDataAccessor.get(ZkCacheBaseDataAccessor.java:391) [helix-core-1.0.1.2402.jar:1.0.1.2402]
```

### Root cause
Jackson was upgraded in helix from 1.x to 2.x. Jackson 1.x does not support Jackson 2.x annotations.

### Proposed solution
According to Jackson's recommendation on GitHub doc: https://github.com/FasterXML/jackson-annotations,
Backwards compatibility:

- You can make Jackson 2 use Jackson 1 annotations with [jackson-legacy-introspector](https://github.com/Laures/jackson-legacy-introspector)

**Comment by narendly** [comment]
Good find!
