### ISSUE TITLE
IllegalArgumentException: wrong number of arguments in testSessionExpirationWithSharedZkClient

### ISSUE THREAD

**Issue by huizhilu** [apache/helix#1660]
```
START TestZkCacheAsyncOpSingleThread testSessionExpirationWithSharedZkClient at Sat Feb 27 22:31:45 PST 2021
4652344 [TestNGInvoker-testSessionExpirationWithSharedZkClient()] ERROR org.apache.helix.TestHelper  - Exception in verify: verifyZkCache
java.lang.IllegalArgumentException: wrong number of arguments
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.helix.TestHelper.verifyWithTimeout(TestHelper.java:186)
        at org.apache.helix.manager.zk.TestZkCacheAsyncOpSingleThread.testSessionExpirationWithSharedZkClient(TestZkCacheAsyncOpSingleThread.java:86)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76)
        at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
        at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
4656532 [TestNGInvoker-testSessionExpirationWithSharedZkClient()] ERROR org.apache.helix.TestHelper  - Exception in verify: verifyZkCache
java.lang.IllegalArgumentException: wrong number of arguments
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.helix.TestHelper.verifyWithTimeout(TestHelper.java:186)
        at org.apache.helix.manager.zk.TestZkCacheAsyncOpSingleThread.testSessionExpirationWithSharedZkClient(TestZkCacheAsyncOpSingleThread.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76)
        at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
        at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by pkuwm** [comment]
@kaisun2000 Could you help with this test? Below code needs to be fixed
```
    TestHelper.verifyWithTimeout("verifyZkCache", 5000, zkCacheInitPaths, accessor._zkCache._cache,
        _gZkClient, true);
```
