### ISSUE TITLE
helix-front e2e tests fail: SessionNotCreatedError: session not created: Chrome version must be between 71 and 75

### ISSUE THREAD

**Issue by micahstubbs** [apache/helix#2075]
### Describe the bug

helix-front e2e tests fail: SessionNotCreatedError: session not created: Chrome version must be between 71 and 75

### To Reproduce

```
# on an Intel Mac:
cd helix-front
npm run e2e
```

### Expected behavior

The end to end tests should run and pass.

### Additional context

```bash
 npm run e2e

> helix-front@1.2.1 e2e /helix/helix-front
> ng e2e

** NG Live Development Server is listening on localhost:49152, open your browser on http://localhost:49152/ **
Date: 2022-05-02T21:56:00.783Z
Hash: 8caa14764854a133a296
Time: 20752ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 683 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 290 kB [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 158 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 13.7 MB [initial] [rendered]
(node:31705) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

webpack: Compiled successfully.
[14:56:00] I/file_manager - creating folder /helix/helix-front/node_modules/protractor/node_modules/webdriver-manager/selenium
[14:56:06] I/update - chromedriver: unzipping chromedriver_2.46.zip
[14:56:07] I/update - chromedriver: setting permissions to 0755 for /helix/helix-front/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.46
[14:56:07] I/launcher - Running 1 instances of WebDriver
[14:56:07] I/direct - Using ChromeDriver directly...
[14:56:08] E/launcher - session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.16.0 x86_64)
[14:56:08] E/launcher - SessionNotCreatedError: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.16.0 x86_64)
    at Object.checkLegacyResponse (/helix/helix-front/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/helix/helix-front/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/helix/helix-front/node_modules/selenium-webdriver/lib/http.js:440:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/helix/helix-front/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/helix/helix-front/node_modules/selenium-webdriver/chrome.js:709:29)
    at Direct.getNewDriver (/helix/helix-front/node_modules/protractor/lib/driverProviders/direct.ts:90:25)
    at Runner.createBrowser (/helix/helix-front/node_modules/protractor/lib/runner.ts:225:39)
    at q.then.then (/helix/helix-front/node_modules/protractor/lib/runner.ts:391:27)
    at _fulfilled (/helix/helix-front/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/helix/helix-front/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/helix/helix-front/node_modules/protractor/node_modules/q/q.js:796:13)
    at /helix/helix-front/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/helix/helix-front/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/helix/helix-front/node_modules/protractor/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[14:56:08] E/launcher - Process exited with error code 199
npm ERR! code ELIFECYCLE
npm ERR! errno 199
npm ERR! helix-front@1.2.1 e2e: `ng e2e`
npm ERR! Exit status 199
npm ERR!
npm ERR! Failed at the helix-front@1.2.1 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2022-05-02T21_56_08_844Z-debug.log
```

**Comment by micahstubbs** [comment]
This looks related https://stackoverflow.com/questions/55810980/using-jest-i-get-cannot-find-type-definition-file-for-jasmine

**Comment by micahstubbs** [comment]
Let's try migrating to Jest https://jestjs.io/docs/migration-guide
