### ISSUE TITLE
[Failed CI Test] helix-front yarn install fails: helix-front/node_modules/vis-network: Cannot read property 'config' of undefined".

### ISSUE THREAD

**Issue by micahstubbs** [apache/helix#2148]
### Describe the bug

Installing this frontend dependency `vis-network` fails in the Ubuntu CI machine. 

```py
[INFO] --- frontend-maven-plugin:1.12.1:yarn (yarn install) @ helix-front ---
[INFO] Running 'yarn install' in /home/runner/work/helix/helix/helix-front
[INFO] yarn install v1.22.18
[INFO] [1/5] Validating package.json...
[INFO] [2/5] Resolving packages...
[INFO] warning request > har-validator@5.1.5: this library is no longer supported
[INFO] [3/5] Fetching packages...
[INFO] [4/5] Linking dependencies...
[INFO] warning " > ngx-vis@3.1.0" has incorrect peer dependency "keycharm@^0.2.0".
[INFO] warning "@angular-builders/jest > jest-preset-angular > ts-jest@27.1.5" has incorrect peer dependency "jest@^27.0.0".
[INFO] warning " > @angular/compiler-cli@13.3.9" has incorrect peer dependency "@angular/compiler@13.3.9".
[INFO] warning nohoist config is ignored in "cypress" because it is not a private package. If you think nohoist should be allowed in public packages, please submit an issue for your use case.
[INFO] [5/5] Building fresh packages...
[INFO] info This package requires node-gyp, which is not currently installed. Yarn will attempt to automatically install it. If this fails, you can run "yarn global add node-gyp" to manually install it.
[INFO] error An unexpected error occurred: "/home/runner/work/helix/helix/helix-front/node_modules/vis-network: Cannot read property 'config' of undefined".
[INFO] error An unexpected error occurred: "/home/runner/work/helix/helix/helix-front/node_modules/vis-network: Cannot read property 'config' of undefined".info If you think this is a bug, please open a bug report with the information provided in "/home/runner/.config/yarn/global/yarn-error.log".****
```

`[INFO] error An unexpected error occurred: "/home/runner/work/helix/helix/helix-front/node_modules/vis-network: Cannot read property 'config' of undefined".
[INFO] error An unexpected error occurred: "/home/runner/work/helix/helix/helix-front/node_modules/vis-network: Cannot read property 'config' of undefined".info If you think this is a bug, please open a bug report with the information provided in "/home/runner/.config/yarn/global/yarn-error.log".****`

https://github.com/apache/helix/runs/6820814450?check_suite_focus=true

### To Reproduce
Steps to reproduce the behavior.

Open a PR and wait for the CI build to run.

### Expected behavior

CI build should succeed, yarn install task for helix-front should succeed.

**Comment by micahstubbs** [comment]
```py
Arguments:
  /tmp/lima/workspace/helix/helix-front/node/node /tmp/lima/workspace/helix/helix-front/node/yarn/dist/bin/yarn.js install

PATH:
  /tmp/lima/workspace/helix/helix-front/node/yarn/dist/bin:/tmp/lima/workspace/helix/helix-front/node:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/sbin:/sbin:/usr/sbin:/sbin:

Yarn version:
  1.22.18

Node version:
  14.17.6

Platform:
  linux arm64

Trace:
  TypeError: /tmp/lima/workspace/helix/helix-front/node_modules/vis-network: Cannot read property 'config' of undefined
      at /tmp/lima/workspace/helix/helix-front/node/yarn/dist/lib/cli.js:34124:120
      at Generator.next (<anonymous>)
      at step (/tmp/lima/workspace/helix/helix-front/node/yarn/dist/lib/cli.js:310:30)
      at /tmp/lima/workspace/helix/helix-front/node/yarn/dist/lib/cli.js:321:13

npm manifest:
  No manifest

yarn manifest:
  No manifest

Lockfile:
  No lockfile
```

**Comment by micahstubbs** [comment]
fixed in https://github.com/apache/helix/pull/2144
