### ISSUE TITLE
helix-front: js dependencies referenced via git hash install failure in private registry

### ISSUE THREAD

**Issue by micahstubbs** [apache/helix#2150]
### Describe the bug
In helix-front the current `"tsickle": "github:angular/tsickle#8f11720637b7bb1c7b0e271e16bebbcdc8189617"` js dependency referenced via git hash causes an install failure in a JFrog Artifactory private package registry.

### To Reproduce
Steps to reproduce the behavior.

```bash
# use an .npmrc configured to point to a private registry
cd helix
./build
```

### Expected behavior

`yarn` install succeeds even when configured to install from a  private JS package registry

**Comment by micahstubbs** [comment]
`tickle@0.46.1` should work since it has as a peer dep: `"typescript": "~4.6.3"`, which is to say "4.6.3 or any higher patch version"

**Comment by micahstubbs** [comment]
Uh-oh. The lastest version published to npm is tsickle@0.46.1. Odd. 

https://www.npmjs.com/package/tsickle

**Comment by micahstubbs** [comment]
Maybe we can remove this dependency altogether?

> Your Angular project should not depend on tsickle unless you've explicitly chosen to use tsickle (and most people shouldn't). If it does, there's some incorrect setup in your dependencies.

https://github.com/angular/tsickle/issues/1322#issuecomment-1021230189

**Comment by micahstubbs** [comment]
Let's test removing `tsickle` as a direct dependency:

- [x] `yarn` successfully installs dependencies
- [x] `yarn type:check:watch` shows 0 TypeScript errors
- [x] `yarn lint` runs and passes `All files pass linting.`
- [] `yarn build` works
- [] `yarn start` works, with 0 errors in the browser console.
- [] `yarn test` runs and passes.

`yarn start` works as expected, and recognizes our proxy config in `proxy.conf.json`.  The Helix UI renders with 0 errors in the browser console.  

<img width="726" alt="Screen Shot 2022-05-24 at 12 51 42 AM" src="https://user-images.githubusercontent.com/2119400/169982366-9906be2e-b053-497e-928a-cbc0a0b3ca86.png">

`yarn test` results

<img width="752" alt="Screen Shot 2022-05-24 at 1 08 23 AM" src="https://user-images.githubusercontent.com/2119400/169982414-5282afad-7d8a-432c-a4e2-4886d622354d.png">

**Comment by micahstubbs** [comment]
```py
yarn build
yarn run v1.22.18
$ rm -rf dist && mkdir dist && ng build --aot --configuration production && tsc -p server
(node:53703) UnhandledPromiseRejectionWarning: Error: Cannot find module 'ajv-formats'
Require stack:
- /helix/apache-helix/helix/helix-front/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/json/schema/registry.js
- /helix/apache-helix/helix/helix-front/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/json/schema/index.js
- /helix/apache-helix/helix/helix-front/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/json/index.js
- /helix/apache-helix/helix/helix-front/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/experimental/jobs/simple-registry.js
- /helix/apache-helix/helix/helix-front/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/experimental/jobs/index.js
- /helix/apache-helix/helix/helix-front/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/experimental.js
- /helix/apache-helix/helix/helix-front/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/index.js
- /helix/apache-helix/helix/helix-front/node_modules/@angular/cli/utilities/config.js
- /helix/apache-helix/helix/helix-front/node_modules/@angular/cli/lib/init.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/helix/apache-helix/helix/helix-front/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/json/schema/registry.js:38:39)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:53703) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:53703) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 2.72s.
```

**Comment by micahstubbs** [comment]
https://www.npmjs.com/package/ajv-formats

JSON Schema formats for Ajv

What is Ajv?

https://www.npmjs.com/package/ajv

Ajv JSON schema validator
The fastest JSON validator for Node.js and browser.

Supports JSON Schema draft-04/06/07/2019-09/2020-12 ([draft-04 support](https://ajv.js.org/json-schema.html#draft-04) requires ajv-draft-04 package) and JSON Type Definition [RFC8927](https://datatracker.ietf.org/doc/rfc8927/).

**Comment by micahstubbs** [comment]
Let's try:

```py
yarn add -D ajv-formats
```

**Comment by micahstubbs** [comment]
```py
yarn build
yarn run v1.22.18
$ rm -rf dist && mkdir dist && ng build --aot --configuration production && tsc -p server
An unhandled exception occurred: Cannot read property 'code' of undefined
See "/private/var/folders/68/yy6n0fn14l30k9tz8pkjdwvc00115x/T/ng-TwCvQA/angular-errors.log" for further details.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

which says:

```py
[error] TypeError: Cannot read property 'code' of undefined
    at addFormats (/helix/apache-helix/helix/helix-front/node_modules/ajv-formats/dist/index.js:30:26)
    at formatsPlugin (/helix/apache-helix/helix/helix-front/node_modules/ajv-formats/dist/index.js:15:5)
    at new CoreSchemaRegistry (/helix/apache-helix/helix/helix-front/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/json/schema/registry.js:96:35)
    at runCommand (/helix/apache-helix/helix/helix-front/node_modules/@angular/cli/models/command-runner.js:118:22)
    at default_1 (/helix/apache-helix/helix/helix-front/node_modules/@angular/cli/lib/cli/index.js:70:69)
```

**Comment by micahstubbs** [comment]
solution: 

https://github.com/ajv-validator/ajv-formats/issues/12#issuecomment-779965228

```
yarn add -D ajv@7.1.0
```

**Comment by micahstubbs** [comment]
Hooray, this fixes the build 🎉

**Comment by micahstubbs** [comment]
Let's increase the maxWarning for the build budget while we are here to 3.47MB which is 3554kb.

```py
yarn build
yarn run v1.22.18
$ rm -rf dist && mkdir dist && ng build --aot --configuration production && tsc -p server
✔ Browser application bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.

Initial Chunk Files           | Names         |  Raw Size | Estimated Transfer Size
main.5842a830071c3192.js      | main          |   3.10 MB |               557.65 kB
styles.cb978aee76fa1bd8.css   | styles        | 303.52 kB |                36.67 kB
polyfills.ff4780c306116b22.js | polyfills     |  73.55 kB |                23.23 kB
runtime.93d35a893ab74671.js   | runtime       |   1.30 kB |               694 bytes

                              | Initial Total |   3.47 MB |               618.24 kB

Build at: 2022-06-15T04:48:23.461Z - Hash: 0cf901e62f73928b - Time: 45420ms

Warning: /helix/apache-helix/helix/helix-front/node_modules/@swimlane/ngx-graph/fesm2015/swimlane-ngx-graph.mjs depends on 'dagre'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /helix/apache-helix/helix/helix-front/node_modules/@swimlane/ngx-graph/fesm2015/swimlane-ngx-graph.mjs depends on 'webcola'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /helix/apache-helix/helix/helix-front/node_modules/ngx-vis/__ivy_ngcc__/fesm2015/ngxvis.js depends on 'vis-network'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /helix/apache-helix/helix/helix-front/node_modules/ngx-vis/__ivy_ngcc__/fesm2015/ngxvis.js depends on 'vis-timeline'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies


✨  Done in 50.44s.
```

**Comment by micahstubbs** [comment]
Let's test removing `tsickle` as a direct dependency:

- [x] `yarn` successfully installs dependencies
- [x] `yarn type:check:watch` shows 0 TypeScript errors
- [x] `yarn lint` runs and passes `All files pass linting.`
- [x] `yarn build` works
