### ISSUE TITLE
Resource Partitions Page table row expansion doesn't work

### ISSUE THREAD

**Issue by micahstubbs** [apache/helix#2210]
### Describe the bug

> Hi,
>
> There might be a bug in helix-ui. 

### To Reproduce
Steps to reproduce the behavior.

> To reproduce:
> On any resource partitions page click on the dropdown arrow of a partition. Expected behavior should be a dropdown list of replicas (as I remember). But now there is no dropdown. Same behavior on both Chrome and Safari.
>
> Also captured the error message from browser console:
ERROR TypeError: Cannot read properties of undefined (reading 'rowDetail')
at e.onSelect (main.20e08eb0c694755f.js:1:1362958)
at main.20e08eb0c694755f.js:1:1360725

### Expected behavior

The table row on the resource partitions page can be expanded.

### Additional context

thanks to @qqu0127  for originally reporting this bug.

**Comment by micahstubbs** [comment]
an instance of this bug https://github.com/swimlane/ngx-datatable/issues/1710

**Comment by micahstubbs** [comment]
fixed in #2211
