### ISSUE TITLE
ZkHelixManager.disconnect() hangs

### ISSUE THREAD

**Issue by tinawenqiao** [apache/helix#454]
In helix 0.9.0，we use ZkHelixManager.disconnect() but found the process still hangs. From stack, we found some threads are running or waiting.

2019-09-09 10:12:15
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode):

"Attach Listener" #27 daemon prio=9 os_prio=0 tid=0x00007f99c8003000 nid=0x19e2 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
    - None

"DestroyJavaVM" #26 prio=5 os_prio=0 tid=0x00007f99f8668000 nid=0x1472 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
    - None

"CallbackHanlder-AsycSubscribe-Singleton" #24 prio=5 os_prio=0 tid=0x00007f99f868c000 nid=0x149b in Object.wait() [0x00007f99dfefd000]
   java.lang.Thread.State: WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    - waiting on <0x00000000d95ea6e8> (a org.apache.helix.common.DedupEventBlockingQueue)
    at java.lang.Object.wait(Object.java:502)
    at org.apache.helix.common.DedupEventBlockingQueue.take(DedupEventBlockingQueue.java:101)
    - locked <0x00000000d95ea6e8> (a org.apache.helix.common.DedupEventBlockingQueue)
    at org.apache.helix.common.DedupEventProcessor.run(DedupEventProcessor.java:41)

   Locked ownable synchronizers:
    - None

"Timer-1" #16 prio=5 os_prio=0 tid=0x00007f99f8647000 nid=0x1491 in Object.wait() [0x00007f99e49e2000]
   java.lang.Thread.State: WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    - waiting on <0x00000000d97166f8> (a java.util.TaskQueue)
    at java.lang.Object.wait(Object.java:502)
    at java.util.TimerThread.mainLoop(Timer.java:526)
    - locked <0x00000000d97166f8> (a java.util.TaskQueue)
    at java.util.TimerThread.run(Timer.java:505)

   Locked ownable synchronizers:
    - None

"ZkClient-EventThread-13-197.3.156.101:2181" #13 daemon prio=5 os_prio=0 tid=0x00007f99f8518000 nid=0x1481 waiting on condition [0x00007f99e4ee8000]
   java.lang.Thread.State: WAITING (parking)
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for  <0x00000000d9668250> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
    at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
    at org.apache.helix.manager.zk.zookeeper.ZkEventThread.run(ZkEventThread.java:63)

   Locked ownable synchronizers:
    - None

"main-EventThread" #12 daemon prio=5 os_prio=0 tid=0x00007f99f850f800 nid=0x1480 waiting on condition [0x00007f99e4fe9000]
   java.lang.Thread.State: WAITING (parking)
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for  <0x00000000d9663490> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
    at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
    at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:502)

   Locked ownable synchronizers:
    - None

"main-SendThread(197.3.156.101:2181)" #11 daemon prio=5 os_prio=0 tid=0x00007f99f8512000 nid=0x147f runnable [0x00007f99e50ea000]
   java.lang.Thread.State: RUNNABLE
    at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
    at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
    at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
    at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
    - locked <0x00000000d96605e0> (a sun.nio.ch.Util$2)
    - locked <0x00000000d96605d0> (a java.util.Collections$UnmodifiableSet)
    - locked <0x00000000d9660160> (a sun.nio.ch.EPollSelectorImpl)
    at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
    at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:349)
    **at org.apache.zookeeper.ClientCnxn$SendThread.run**(ClientCnxn.java:1144)

   Locked ownable synchronizers:
    - None

"ZkClient-EventThread-10-197.3.156.101:2181" #10 daemon prio=5 os_prio=0 tid=0x00007f99f84d9000 nid=0x147e waiting on condition [0x00007f99e51eb000]
   java.lang.Thread.State: WAITING (parking)
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for  <0x00000000d9663b68> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
    at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
    at org.apache.helix.manager.zk.zookeeper.ZkEventThread.run(ZkEventThread.java:63)

   Locked ownable synchronizers:
    - None

"Service Thread" #7 daemon prio=9 os_prio=0 tid=0x00007f99f80c1000 nid=0x147b runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
    - None

"C1 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007f99f80bc800 nid=0x147a waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
    - None

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007f99f80b9800 nid=0x1479 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
    - None

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007f99f80b8000 nid=0x1478 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
    - None

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007f99f807c800 nid=0x1477 in Object.wait() [0x00007f99e6264000]
   java.lang.Thread.State: WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    - waiting on <0x00000000d9717d88> (a java.lang.ref.ReferenceQueue$Lock)
    at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
    - locked <0x00000000d9717d88> (a java.lang.ref.ReferenceQueue$Lock)
    at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
    at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

   Locked ownable synchronizers:
    - None

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007f99f807a000 nid=0x1476 in Object.wait() [0x00007f99e6365000]
   java.lang.Thread.State: WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    - waiting on <0x00000000d9717fa0> (a java.lang.ref.Reference$Lock)
    at java.lang.Object.wait(Object.java:502)
    at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
    - locked <0x00000000d9717fa0> (a java.lang.ref.Reference$Lock)

   Locked ownable synchronizers:
    - None

"VM Thread" os_prio=0 tid=0x00007f99f8075000 nid=0x1475 runnable

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007f99f8020800 nid=0x1473 runnable

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007f99f8022800 nid=0x1474 runnable

"VM Periodic Task Thread" os_prio=0 tid=0x00007f99f80c4000 nid=0x147c waiting on condition

JNI global references: 255

**Comment by dasahcc** [comment]
@tinawenqiao . I think the disconnect waits for your piled up events queue to be cleared up, since HelixManager is trying to reset all handlers including callback handler.

**Comment by tinawenqiao** [comment]
Yes, the manager has a callback handler:
_manager.getMessagingService().sendAndWait(recipientCriteria, msg, callbackOnReply, 30000);_
But I need to end the program after that, then I call disconnect method. So what should I do? Is there another method to end the program which has a helix manger.

**Comment by dasahcc** [comment]
@tinawenqiao Two options are here:
1. You can reduce your message timeout and try to handle it with retry or some other logic. To make sure your message send is not a blocking call. Thus the disconnect can happen gracefully processed.
2. If you think your hanging message is not that matter, you can shutdown service by killing the JVM.
