### ISSUE TITLE
Resource not found in the instance capacity reporting logic

### ISSUE THREAD

**Issue by jiajunwang** [apache/helix#565]
I believe this introduced by the recent metric code. @pkuwm, could you please take a look?

org.apache.helix.HelixException: Cannot find the resource ideal state for resource: Test-DB-createTestDBs1
	at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.parseAllReplicas(ClusterModelProvider.java:237)
	at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModel(ClusterModelProvider.java:73)
	at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModelFromCurrentState(ClusterModelProvider.java:109)
	at org.apache.helix.controller.stages.CurrentStateComputationStage.reportInstanceCapacityMetrics(CurrentStateComputationStage.java:242)
	at org.apache.helix.controller.stages.CurrentStateComputationStage.process(CurrentStateComputationStage.java:85)
	at org.apache.helix.controller.pipeline.Pipeline.handle(Pipeline.java:68)
	at org.apache.helix.controller.GenericHelixController.handleEvent(GenericHelixController.java:674)
	at org.apache.helix.controller.GenericHelixController.access$400(GenericHelixController.java:116)
	at org.apache.helix.controller.GenericHelixController$ClusterEventProcessor.run(GenericHelixController.java:1205)

**Comment by pkuwm** [comment]
I am working on this. Thanks for reporting @jiajunwang

**Comment by pkuwm** [comment]
Log sample:

```
START testZoneIsolationWithInstanceTag at Mon Nov 04 18:45:51 PST 2019
129010 [HelixController-async_tasks-CLUSTER_TestWagedRebalanceFaultZone] ERROR org.apache.helix.controller.stages.CurrentStateComputationStage  - Failed to report instance capacity metrics.
org.apache.helix.HelixException: Cannot find the resource ideal state for resource: Test-DB-testZoneIsolationWithInstanceTag1
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.parseAllReplicas(ClusterModelProvider.java:237)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModel(ClusterModelProvider.java:73)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModelFromCurrentState(ClusterModelProvider.java:109)
        at org.apache.helix.controller.stages.CurrentStateComputationStage.lambda$reportInstanceCapacityMetrics$0(CurrentStateComputationStage.java:242)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
129154 [HelixController-async_tasks-CLUSTER_TestWagedRebalanceFaultZone] ERROR org.apache.helix.controller.stages.CurrentStateComputationStage  - Failed to report instance capacity metrics.
org.apache.helix.HelixException: Cannot find the resource ideal state for resource: Test-DB-testZoneIsolationWithInstanceTag1
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.parseAllReplicas(ClusterModelProvider.java:237)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModel(ClusterModelProvider.java:73)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModelFromCurrentState(ClusterModelProvider.java:109)
        at org.apache.helix.controller.stages.CurrentStateComputationStage.lambda$reportInstanceCapacityMetrics$0(CurrentStateComputationStage.java:242)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
129193 [HelixController-async_tasks-CLUSTER_TestWagedRebalanceFaultZone] ERROR org.apache.helix.controller.stages.CurrentStateComputationStage  - Failed to report instance capacity metrics.
org.apache.helix.HelixException: Cannot find the resource ideal state for resource: Test-DB-testZoneIsolationWithInstanceTag1
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.parseAllReplicas(ClusterModelProvider.java:237)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModel(ClusterModelProvider.java:73)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModelFromCurrentState(ClusterModelProvider.java:109)
        at org.apache.helix.controller.stages.CurrentStateComputationStage.lambda$reportInstanceCapacityMetrics$0(CurrentStateComputationStage.java:242)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
129296 [HelixController-async_tasks-CLUSTER_TestWagedRebalanceFaultZone] ERROR org.apache.helix.controller.stages.CurrentStateComputationStage  - Failed to report instance capacity metrics.
org.apache.helix.HelixException: Cannot find the resource ideal state for resource: Test-DB-testZoneIsolationWithInstanceTag1
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.parseAllReplicas(ClusterModelProvider.java:237)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModel(ClusterModelProvider.java:73)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModelFromCurrentState(ClusterModelProvider.java:109)
        at org.apache.helix.controller.stages.CurrentStateComputationStage.lambda$reportInstanceCapacityMetrics$0(CurrentStateComputationStage.java:242)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
129329 [HelixController-async_tasks-CLUSTER_TestWagedRebalanceFaultZone] ERROR org.apache.helix.controller.stages.CurrentStateComputationStage  - Failed to report instance capacity metrics.
org.apache.helix.HelixException: Cannot find the resource ideal state for resource: Test-DB-testZoneIsolationWithInstanceTag1
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.parseAllReplicas(ClusterModelProvider.java:237)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModel(ClusterModelProvider.java:73)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModelFromCurrentState(ClusterModelProvider.java:109)
        at org.apache.helix.controller.stages.CurrentStateComputationStage.lambda$reportInstanceCapacityMetrics$0(CurrentStateComputationStage.java:242)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
END testZoneIsolationWithInstanceTag at Mon Nov 04 18:45:53 PST 2019, took: 1841ms.
START testZoneIsolation at Mon Nov 04 18:45:53 PST 2019
130691 [HelixController-async_tasks-CLUSTER_TestWagedRebalanceFaultZone] ERROR org.apache.helix.controller.stages.CurrentStateComputationStage  - Failed to report instance capacity metrics.
org.apache.helix.HelixException: Cannot find the resource ideal state for resource: Test-DB-testZoneIsolation0
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.parseAllReplicas(ClusterModelProvider.java:237)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModel(ClusterModelProvider.java:73)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModelFromCurrentState(ClusterModelProvider.java:109)
        at org.apache.helix.controller.stages.CurrentStateComputationStage.lambda$reportInstanceCapacityMetrics$0(CurrentStateComputationStage.java:242)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
130866 [HelixController-async_tasks-CLUSTER_TestWagedRebalanceFaultZone] ERROR org.apache.helix.controller.stages.CurrentStateComputationStage  - Failed to report instance capacity metrics.
org.apache.helix.HelixException: Cannot find the resource ideal state for resource: Test-DB-testZoneIsolation0
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.parseAllReplicas(ClusterModelProvider.java:237)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModel(ClusterModelProvider.java:73)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModelFromCurrentState(ClusterModelProvider.java:109)
        at org.apache.helix.controller.stages.CurrentStateComputationStage.lambda$reportInstanceCapacityMetrics$0(CurrentStateComputationStage.java:242)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
130893 [HelixController-async_tasks-CLUSTER_TestWagedRebalanceFaultZone] ERROR org.apache.helix.controller.stages.CurrentStateComputationStage  - Failed to report instance capacity metrics.
org.apache.helix.HelixException: Cannot find the resource ideal state for resource: Test-DB-testZoneIsolation0
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.parseAllReplicas(ClusterModelProvider.java:237)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModel(ClusterModelProvider.java:73)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModelFromCurrentState(ClusterModelProvider.java:109)
        at org.apache.helix.controller.stages.CurrentStateComputationStage.lambda$reportInstanceCapacityMetrics$0(CurrentStateComputationStage.java:242)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
131085 [HelixController-async_tasks-CLUSTER_TestWagedRebalanceFaultZone] ERROR org.apache.helix.controller.stages.CurrentStateComputationStage  - Failed to report instance capacity metrics.
org.apache.helix.HelixException: Cannot find the resource ideal state for resource: Test-DB-testZoneIsolation1
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.parseAllReplicas(ClusterModelProvider.java:237)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModel(ClusterModelProvider.java:73)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModelFromCurrentState(ClusterModelProvider.java:109)
        at org.apache.helix.controller.stages.CurrentStateComputationStage.lambda$reportInstanceCapacityMetrics$0(CurrentStateComputationStage.java:242)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
131143 [HelixController-async_tasks-CLUSTER_TestWagedRebalanceFaultZone] ERROR org.apache.helix.controller.stages.CurrentStateComputationStage  - Failed to report instance capacity metrics.
org.apache.helix.HelixException: Cannot find the resource ideal state for resource: Test-DB-testZoneIsolation1
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.parseAllReplicas(ClusterModelProvider.java:237)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModel(ClusterModelProvider.java:73)
        at org.apache.helix.controller.rebalancer.waged.model.ClusterModelProvider.generateClusterModelFromCurrentState(ClusterModelProvider.java:109)
        at org.apache.helix.controller.stages.CurrentStateComputationStage.lambda$reportInstanceCapacityMetrics$0(CurrentStateComputationStage.java:242)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
END testZoneIsolation at Mon Nov 04 18:45:55 PST 2019, took: 1702ms.
```

**Comment by jiajunwang** [comment]
@pkuwm , could you please confirm if this issue has been fixed?

**Comment by pkuwm** [comment]
@jiajunwang  I confirm this is fixed. We can close this issue.
