### ISSUE TITLE
java.lang.NullPointerException  in unit tests

### ISSUE THREAD

**Issue by pkuwm** [apache/helix#566]
START testClusterExpansion at Mon Nov 04 10:27:57 PST 2019
80422 [HelixTaskExecutor-message_handle_thread] ERROR org.apache.helix.messaging.handling.HelixTask  - Exception while executing a message. java.lang.NullPointerException msgId: 2573967b-fb75-46b1-8e6c-d4bfbb513837 type: STATE_TRANSITION
java.lang.NullPointerException
        at java.util.HashMap.putMapEntries(HashMap.java:500)
        at java.util.HashMap.<init>(HashMap.java:489)
        at org.apache.helix.ZNRecord.lambda$new$0(ZNRecord.java:106)
        at java.util.TreeMap.forEach(TreeMap.java:1005)
        at org.apache.helix.ZNRecord.<init>(ZNRecord.java:106)
        at org.apache.helix.ZNRecord.<init>(ZNRecord.java:94)
        at org.apache.helix.ZNRecordDelta.<init>(ZNRecordDelta.java:51)
        at org.apache.helix.messaging.handling.HelixStateTransitionHandler.postHandleMessage(HelixStateTransitionHandler.java:230)
        at org.apache.helix.messaging.handling.HelixStateTransitionHandler.handleMessage(HelixStateTransitionHandler.java:371)
        at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:97)
        at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

It seems related to ZNRecord deep copy commit: https://github.com/apache/helix/commit/2a335cf73ac65b53fd2b06c6b1ee8c70553d30b1
When the nested map value is null, when v == null, new HashMap<>(v) gives java.lang.NullPointerException

**Comment by narendly** [comment]
@pkuwm Did you not run the tests before marking the commit as ready?

**Comment by pkuwm** [comment]
@narendly The tests were run before PR and also before merging the code. But the NPE did not fail the tests and so the tests were all passed. I did not check all the logs for NPE that time.
Currently we still have NPE for other tests and the tests all pass. I will create an issue for recording the NPE in other tests.
