### ISSUE TITLE
Question on CrushEd rebalance algorithm and MasterSalve state model for Pinot

### ISSUE THREAD

**Issue by jackjlli** [apache/helix#680]
This is Jack from Pinot team. We have a discussion on the chosen algorithm and the state model for one of our resource in Pinot.
The resource is called `leadControllerResource`. The purpose of that is to assign Pinot controllers to different partitions, so that each controller can be the leaders of some partitions and work for the Pinot tables that the relevant partition belong to. And we don't want the partition leadership gets changed frequently.

Currently the rebalance algorithm that we are using is CrushED, and the state model is MasterSlave. We're using them in Production now.

@kishoreg points out that the model can be simplified as auto rebalance strategy and OnlineOffline state model. 

So do you have any comments on that? Given the fact that CrushEd and MasterSlave are being used in Production, how hard is it to migrate to the new ones?

Here is the stack trace we've seen in 0.8.4 when starting the very first Pinot controller shown in helix controller log:
```
Event a2016980_DEFAULT : Error computing assignment for resource leadControllerResource. Skipping.
java.lang.IllegalStateException: null
        at org.apache.helix.controller.rebalancer.strategy.crushMapping.CRUSHPlacementAlgorithm$Selector.select(CRUSHPlacementAlgorithm.java:308) ~[helix-core-0.8.4.jar:0.8.4]
        at org.apache.helix.controller.rebalancer.strategy.crushMapping.CRUSHPlacementAlgorithm.select(CRUSHPlacementAlgorithm.java:119) ~[helix-core-0.8.4.jar:0.8.4]
        at org.apache.helix.controller.rebalancer.strategy.CrushRebalanceStrategy.doSelect(CrushRebalanceStrategy.java:173) ~[helix-core-0.8.4.jar:0.8.4]
        at org.apache.helix.controller.rebalancer.strategy.CrushRebalanceStrategy.select(CrushRebalanceStrategy.java:140) ~[helix-core-0.8.4.jar:0.8.4]
        at org.apache.helix.controller.rebalancer.strategy.CrushRebalanceStrategy.computePartitionAssignment(CrushRebalanceStrategy.java:92) ~[helix-core-0.8.4.jar:0.8.4]
        at org.apache.helix.controller.rebalancer.strategy.CrushRebalanceStrategy.computePartitionAssignment(CrushRebalanceStrategy.java:48) ~[helix-core-0.8.4.jar:0.8.4]
        at org.apache.helix.controller.rebalancer.strategy.AbstractEvenDistributionRebalanceStrategy.computePartitionAssignment(AbstractEvenDistributionRebalanceStrategy.java:88) ~[helix-core-0.8.4.jar:0.8.4]
        at org.apache.helix.controller.rebalancer.strategy.AbstractEvenDistributionRebalanceStrategy.computePartitionAssignment(AbstractEvenDistributionRebalanceStrategy.java:49) ~[helix-core-0.8.4.jar:0.8.4]
        at org.apache.helix.controller.rebalancer.AutoRebalancer.computeNewIdealState(AutoRebalancer.java:128) ~[helix-core-0.8.4.jar:0.8.4]
        at org.apache.helix.controller.rebalancer.AutoRebalancer.computeNewIdealState(AutoRebalancer.java:51) ~[helix-core-0.8.4.jar:0.8.4]
        at org.apache.helix.controller.stages.BestPossibleStateCalcStage.computeResourceBestPossibleState(BestPossibleStateCalcStage.java:244) ~[helix-core-0.8.4.jar:0.8.4]
        at org.apache.helix.controller.stages.BestPossibleStateCalcStage.compute(BestPossibleStateCalcStage.java:120) ~[helix-core-0.8.4.jar:0.8.4]
        at org.apache.helix.controller.stages.BestPossibleStateCalcStage.process(BestPossibleStateCalcStage.java:76) ~[helix-core-0.8.4.jar:0.8.4]
        at org.apache.helix.controller.pipeline.Pipeline.handle(Pipeline.java:68) ~[helix-core-0.8.4.jar:0.8.4]
        at org.apache.helix.controller.GenericHelixController.handleEvent(GenericHelixController.java:640) ~[helix-core-0.8.4.jar:0.8.4]
        at org.apache.helix.controller.GenericHelixController.access$400(GenericHelixController.java:117) ~[helix-core-0.8.4.jar:0.8.4]
        at org.apache.helix.controller.GenericHelixController$ClusterEventProcessor.run(GenericHelixController.java:1168) ~[helix-core-0.8.4.jar:0.8.4]

```

**Comment by jiajunwang** [comment]
I had some discussion with Jack offline. My take away is that the AutoRebalanceStrategy with OnlineOffline state model might work for Pinot for now. But it has some limitations and may impact future changes. For example, this strategy is not rack-aware. As for the OnlineOffline state model, once there are more than 2 replicas, we will have multiple online replicas. I assume it might cause issues.

In addition, I'm not sure what does "simplified" mean for Pinot? The CrushEd algorithm is internally more complicated, but it is more stable and performs better than the legacy strategy. So eventually, the CrushEd strategy should help to simplify the application code more. I remember it is part of the reason we decided to go with the CrushEd strategy.

@dasahcc @lei-xia Could you please also take a look in case I missed anything.

**Comment by kishoreg** [comment]
Thanks Jiajun for the response. Pinot doesn't need rack-awareness for
controllers since they are stateless and each partition (which is a
pinot-table) is independent.

Out of curiosity, what is the problem with OnlineOffline model if there are
more than 2 replicas?

CrushEd implementation throws an illegal exception even though the scenario
is valid and happens every time at startup. We don't see this behavior with
AutoRebalanceStrategy.

**Comment by jiajunwang** [comment]
Hi @kishoreg,

I agree with the first point, that's why I think there is no problem to switch for now.

Regarding the OnlineOffline state model, Helix will try to bring all the replicas to the topstate "online". But what Pinot needs is only one topstate replica, right? That is the thing in my mind. Please correct me if I misunderstand the usage.

I also took a quick look at the illegal exception thread. On my understanding, the error log happens due to a lack of participants during the initial process. Once there are enough participants to become alive, the controller will be able to rebalance automatically. The only difference between CrushEd and AutoRebalanceStrategy is that CrushEd complains about it and print an error log, while the AutoRebalanceStrategy silently returns an empty mapping without printing error log.
Given this, it won't cause any trouble. Could you please elaborate on the valid scenario that you mentioned? If we are actually talking about different scenarios, we can help to revisit the logic and see if there is any issue in the CrushEd strategy.

**Comment by kishoreg** [comment]
The algorithm should not throw an exception, that’s not part of the
strategy interface/contract and is not consistent with other strategies.

Throwing illegal state exception is not very useful.

**Comment by jiajunwang** [comment]
The reason for this Exception, as far as I can remember, is to terminate the pipeline if the rebalancer cannot calculate the new mapping. Otherwise, the later stages will execute based on an incomplete or even empty mapping. This could be dangerous.
But I agree that we should be able to handle the empty cluster case more gracefully. In this case, an empty mapping is the only option that the rebalancer can return. Let me talk with the team at tomorrow's standup meeting.

**Comment by jackjlli** [comment]
From the users perspective, the exception shouldn't be thrown at the first place because it's misleading to the users that they thought they've done sth wrong. 
It'd be good to better handle this scenario by avoiding any exception when starting.

Another dimension is that all the algorithm behaviors should be uniformed.

**Comment by jackjlli** [comment]
This is the workaround regarding to this issue:
https://github.com/apache/incubator-pinot/pull/4985
The idea is that, before the first Pinot controller full starts up, the leadControllerResource won't turn on FULL-AUTO rebalance strategy.

We'll also wait for Helix team to uniform the algorithm behaviors before closing this issue.
